### ISSUE TITLE
PAIR | Workaround - Taken/Traces verwijderen in Reserveringen

### ISSUE THREAD

**Issue by renskejetten** [renskejetten/CUSTOMER-SUCCESS#12]
**Oorspronkelijke vraag:**
Hoe kunnen we de ‘taken’/ traces kunnen verwijderen in reservaties?
De mogelijkheid om te annuleren/verwijderen is niet meer mogelijk. Enkel toevoegen is nog een optie.

**Workaround**:
Wanneer je op het vinkje/vakje klikt, krijg je wel alle opties om de taak te bewerken.
Ik stuur je hierbij een filmpje voor een duidelijk beeld

**Intercom link**:
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/5248404/conversations/36000017027
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000016290?q=SUP-283959&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

https://user-images.githubusercontent.com/57394896/145006250-40e1d27c-2ae9-4af5-a5b6-5c58838fde4c.mov

.

**Comment by WillemFlow** [comment]
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000016290?q=SUP-283959&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by WillemFlow** [comment]
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000016358?q=SUP-283959&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by WillemFlow** [comment]
Gemeld door Eveline van AON Plaza
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000016218?q=SUP-283959&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by WillemFlow** [comment]
Gemeld door Raphael Vayamundo:
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000016277?q=SUP-283959&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by WillemFlow** [comment]
Gemeld door ESH:
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000016264?q=SUP-283959&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all
