### ISSUE TITLE
 IFC | POS | Onbekend artikel

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#20]
**Vraag**
De klant stuurt: wij krijgen vanuit de kassa 'POS Onbekend' artikelen, welke zijn dit?

**Oplossing**
Uitzoeken welke artikelen
- Dit kan aan de hand van de 'Journal by product group' rapportage, je filtert dan op de juiste datum en bij artikel vink je POS Onbekend aan. De datum weet je normaliter van het voorbeeld van de klant. Zo niet, selecteer een wat grotere periode om te kijken of daar een onbekend artikel in zit (bijv. afgelopen maand).
Op het rapportage zie je dan ook een bonnummer.
![Screenshot 2021-12-29 at 15 13 22](https://user-images.githubusercontent.com/95683711/147671197-e9ae6f93-dbfe-480c-98ab-c6b7b27adac4.png)

![Screenshot 2021-12-29 at 15 13 38](https://user-images.githubusercontent.com/95683711/147671173-5258a6d6-9ecc-4498-bff9-4d53f4ee34b4.png)

Zoals je ziet, staat er als gast System, Cash Interface (passerby invoice) met een bonnummer.
Je kunt dan zoeken bij Cashiering > Billing, vervolgens open je de rekening en het juiste bonnetje voor de details.
De passerby invoice vind je dan hier:

![Screenshot 2021-12-29 at 15 10 30](https://user-images.githubusercontent.com/95683711/147671480-0422ab6a-0142-4794-8b7b-3acdf987b6d1.png)

- Je ziet dan op het rapportage, naar welke reservering 'POS Onbekend' is geboekt, je kunt dit dan dubbel checken op de rekening:
![bon 97237](https://user-images.githubusercontent.com/95683711/146798567-b74c7538-4f8b-43bb-8afe-8558b62748fd.png)

Vervolgens open je in Simba de POS Interface > Archive browser > Open je de log files van de juiste dag (de dag waarop onbekende artikelen zijn geboekt) en zoek (ctrl+F of cmnd+F) je op de bonnummer. Kijk goed naar de prijs en de rekening, om er achter te komen welke artikel 'onbekend' staat.

![Screenshot 2021-12-13 at 17 20 25](https://user-images.githubusercontent.com/95683711/145849590-27161392-238d-4132-bc5a-1402ed1dde37.png)

<img width="1674" alt="pos" src="https://user-images.githubusercontent.com/95683711/147464058-70edbbd1-f347-4c4c-b02e-71e9b86bb736.png">

![logfile pos](https://user-images.githubusercontent.com/95683711/147668315-b693a236-b8f0-4c85-99b6-99dd00ec1cf1.png)

In dit geval zie je dus dat het bedrag van €13 overeenkomt met het product; 'Langoustine'.

Laat het hotel weten, welke artikelen dit zijn. Indien deze artikelen binnen een categorie horen, dienen ze dit zelf te koppelen. 
Wanneer het over categorieën gaat, dienen wij dit te mappen voor het hotel. Hiervoor hebben wij van het hotel het bijbehorende ID nodig. 

Zie onderstaande link voor communicatie met hotel en alledrie de voorbeelden van de POS Onbekend:
**Link:** [Conversation with Receptie - De Lunterse Boer](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000015454)

**Comment by WillemFlow** [comment]
Conversatie met Reina weghalen

Voorbeeld log;
welke zoekterm zoeken, omcirkelen welke data van belang is en wat het betekent

**Comment by AudreyAdamus** [comment]
<img width="1674" alt="Schermafbeelding 2021-12-27 om 11 37 02" src="https://user-images.githubusercontent.com/72549907/147463861-79d80517-7e58-4af7-ad24-54cac6b64feb.png">

tip

**Comment by raoulhendriks** [comment]
RH 29-12: 'als je weet op welke dag 'POS Onbekend' artikelen zijn geboekt'

Hoe kom ik hier achter?

WV: aangepast

**Comment by TomMestrom** [comment]
Vraag
''Wij krijgen vanuit de kassa 'POS Onbekend' artikelen'' Krijgen we dit vanuit de klant of is dit een melding die wij zelf ontvangen? 

ZW: aangepast

**Comment by TomMestrom** [comment]
Open je de log files van de **juiste dag** en zoek (ctrl+F of cmnd+F) je op de bonnummer. Misschien specifieker zijn in wat de juiste dag is? 

ZW: aangepast

**Comment by raoulhendriks** [comment]
'Je ziet dan op het rapportage,' --> Misschien een foto toevoegen van deze rapportages, voor visualisatie :D

**Comment by TomMestrom** [comment]
Kijk goed naar de prijs en de rekening, om er achter te komen welke artikel 'onbekend' staat. --> misschien voorbeeld toevoegen hoe de prijzen overeenkomen? a.d.v. bovenstaand voorbeeld weet ik nu niet welk artikel 'onbekend' is

WV: in die afbeeldingen eronder staat het voorbeeld.
