### ISSUE TITLE
PMS | MICE | PM nummer-rekening toewijzen aan groep of evenement 

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#23]
**Vraag**
Het hotel geeft aan dat ze niet de juiste factuur kunnen toewijzen aan de groep of MICE evenement, omdat ze de factuur niet in het overzicht kunnen zien.

https://jira-live.protel.net/servicedesk/customer/portal/232/SUP-7670

**Oplossing**
- Een artikel op de factuur (PM) opboeken > factuur toewijzen > geboekte artikel annuleren
- Fixed charges toevoegen (PM) > factuur toewijzen > fixed charges annuleren/verwijderen
 
**Voorbeeld e-mail:**
Beste,

﻿Bedankt voor je e-mail.
﻿Dit komt omdat er geen kosten op de factuur zijn geboekt, dan is deze niet vindbaar.
﻿Dit is reeds doorgestuurd naar het development team van protel, maar voor nu zou je iets kunnen opboeken en weer tegenboeken om de rekening zichtbaar te krijgen.
﻿
﻿We zullen je op de hoogte houden van onze escalatie naar protel Development.
﻿Ik hoor graag of het duidelijk is!
﻿
﻿Met vriendelijke groet,

**Link:** [Conversation with reserveringen@eigentijdserf.nl](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000017060)

**Customer:** [reserveringen@eigentijdserf.nl](https://app.intercom.com/a/apps/fagrlzth/users/5f59d39e37c89c102bfa0eb1/all-conversations)
**Customer ID:** 541c7055-3045-4518-afeb-01740c18e352
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000017060) when this issue is closed.

**Comment by WillemFlow** [comment]
bij bugs --> Jira ticket toevoegen
