### ISSUE TITLE
DRAFT | PMS | Rates koppelen Cubilis --> Nog afmaken

### ISSUE THREAD

**Issue by raoulhendriks** [renskejetten/CUSTOMER-SUCCESS#24]
**Vraag**
Kunnen jullie deze rates voor ons koppelen met Cubilis?

**Oplossing**
Voordat je de rates van Protel met Cubilis kunt koppelen is het van belang dat je de bijbehorende ID's ontvangen hebt van zowel Protel als Cubilis.

**Comment by AudreyAdamus** [comment]
even een kleine note wanneer ID niet zichtbaar is, moet de klant contact opnemen met cubilis
