### ISSUE TITLE
PMS | IDS | Hoe zoek je uit welke prijs we sturen?

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#25]
**Vraag**
Het hotel geeft aan, dat er een verkeerde prijs online staat/ voor een verkeerde prijs een boeking is gemaakt.

**Oplossing**
We hebben de volgende informatie nodig van de klant:
- Tarief
- Kamertype
- Datum
- (eventueel) reservering die gemaakt is voor een verkeerde prijs (bovenstaande info staat hier dan in).

Voorbeeld:
Voor mijn best available rate bij de standard King zie ik op 3 januari 2022 online een prijs staan van €100 maar dit moet €121 zijn.

Wat je in de PMS kunt checken: 
- Wat is de prijs in de daily rates
- Wat is de prijs in de reservering aanvraag (bij een virtual rate bijvoorbeeld, die niet in de daily rates staat)
Deze twee prijzen komen normaliter overeen, en de prijs in de daily rates is wat protel stuurt naar de IDS en de IDS naar de channel manager.

In de IDS kun je controleren of wij dit ook daadwerkelijk sturen.
1. Open de IDS 
2. Open de export log files 
3. Exported for (vul hier de periode in waarvoor wij het sturen)
4. Exported between (vul hier de periode in wanneer wij het gestuurd hebben)
5. Filter op kamertype en Tarief code (check bij **PMS settings** wat de codes zijn)
6. Zorg dat je het tabje rate/restriction aangeklikt hebt. 
7. Druk op refresh **(wacht tot de data geladen wordt en druk niet nog eens op dit knopje)**

![Screenshot 2022-01-02 at 13 59 45](https://user-images.githubusercontent.com/95683711/147876634-28599704-c509-4f47-a2c9-cf332d186a69.png)

![ratecode](https://user-images.githubusercontent.com/95683488/147745425-14a20451-f7ad-4196-8e08-6be5c869a3ff.png)
![Room type](https://user-images.githubusercontent.com/95683488/147745424-00880791-3ed6-48c3-b8aa-38945a0964af.png)
![export log files](https://user-images.githubusercontent.com/95683488/147745426-cc6e116b-76df-4be0-abe0-05cc12cde904.png)

Wij sturen in bovenstaand geval voor 1 persoon €123 en voor 2 personen €121.

**Indien wij de prijs correct sturen:**
- Indien wij de prijs correct sturen en het hotel alles goed in protel heeft ingesteld (ofwel, de prijs komt overeen met wat in de daily rates staat):
1. Stuur een full update en vraag aan het hotel of ze het nog eens kunnen controleren.
2. Indien dit niet helpt, zet de channel manager in CC en laat ze weten welke prijs wij sturen. Vraag hierbij waarom dit niet overgenomen wordt en voeg de XML toe waarin staat wat wij sturen.

Export log file:
![log file history](https://user-images.githubusercontent.com/95683488/146788936-5dc1e855-d8f7-4d77-a592-404f31b2b944.png)

- Indien wij de prijs correct sturen, maar het hotel aangeeft dat dit niet de correcte prijs is.
Vraag het hotel wat de prijs zou moeten zijn in protel volgens het hotel en controleer de volgende zaken:
1. Wat is er ingesteld in de daily rates?
2. Zijn er op het tarief restricties ingesteld?
3. Het tarief zelf: zijn er in de berekeningen bijvoorbeeld periodes ingesteld?

Geef het hotel aan waarom de prijs is wat het momenteel is en laat ze dit aanpassen indien nodig.

**Intercom ticket:** https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000017511?q=revcontrol&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all  > Hiervoor hoefde ik niet eens IDS te openen, bijvoorbeeld.

**Indien wij de prijs niet correct sturen**
#73

**Comment by WillemFlow** [comment]
Susy & Willem --> belletje

**Comment by ZsuzsannaWu** [comment]
29-12 ZW: als we prijzen incorrect sturen, dienen we dit verder uit te zoeken. Hierover maken we een nieuwe GitHub issue.

**Comment by TomMestrom** [comment]
RevControl? -->?

**Comment by raoulhendriks** [comment]
Wat zijn alle benodigheden die we zeker van het hotel moeten hebben om alles te kunnen checken

**Oplossing**
We hebben de volgende informatie nodig van de klant:
- Tarief
- Kamertype
- Datum
- (eventueel) reservering die gemaakt is voor een verkeerde prijs (bovenstaande info staat hier dan in).

**Comment by TomMestrom** [comment]
06-06-22 Tm: is de nieuwe GitHub issue al aangemaakt zoals omschreven in de comment bij Susy op 29-12-21 ? 

Anders wellicht handig om de de link van dat ticket op te nemen achter:

Indien wij de prijs niet correct sturen
xxx

Voor de rest helemaal top uitgelegd !!

09-01-22 ZW: nee, gaan we doen!

**Comment by raoulhendriks** [comment]
Verwijzing naar nieuw github issue maken 

ZW: done :)

**Comment by TomMestrom** [comment]
Thanks Susy!
