### ISSUE TITLE
PMS | IDS | Hoe zoek je uit welke beschikbaarheid we sturen? 

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#26]
**Vraag**
Het hotel geeft aan dat ze problemen hebben met de beschikbaarheid, bijvoorbeeld een overboeking of niet/wel boekbaar op bepaalde dagen.

**Belangrijke informatie**
*In de IDS is er een export en een import functie, wanneer er data geëxporteerd wordt, kan er geen boeking geïmporteerd worden. Er zijn meerdere mogelijke oorzaken voor een overboeking:
- Een kamer wordt op hetzelfde moment geboekt bij verschillende online kanalen.
- Op het moment van de overboeking, is er manueel (door een receptioniste) een boeking gemaakt
- Door het hotel zelf aangebrachte wijzigingen kwam beschikbaarheid vrij
- Storing bij protel (data wordt niet geüpdatet tussen protel en IDS)
- Een lange export waardoor de data niet op tijd geüpdatet is in de online kanalen

*Er zit een tijdverschil tussen protel en de IDS door verschillende tijdzones (1 of 2 uur verschil met IDS)
Wintertijd verschil: IDS 09:00 = protel 10:00 
Zomertijd verschil: IDS 08:00 = protel 10:00 
Je kunt in de bovenste balk van de IDS ook de timestamp checken en deze vergelijken met je computer tijd:
![Screenshot 2021-12-14 at 17 19 18](https://user-images.githubusercontent.com/95683711/146147621-7f2117e2-fb90-4b23-bb42-65c5887f175e.png)

*Wij sturen de beschikbaarheid specifiek per kamertype en tarief. Dus als wij voor een kamer 0 beschikbaarheid sturen, moet dit in combinatie zijn geweest met het tarief waarop de overboeking is binnen gekomen.
voorbeeld:
Overboeking wordt gemaakt op kamertype **Deluxe** en Tarief **Fully Flexible**.
Wij sturen dan een beschikbaarheid voor kamertype Deluxe en alle verschillende tarieven. Een beschikbaarheid van 0 die bijv. gestuurd wordt voor het kamertype **deluxe** en het tarief **Non Refundable**, heeft bij de channel manager geen invloed op de beschikbaarheid voor de Fully Flexible.
Indien de overboeking dus op de **Fully Flexible** is geboekt, kunnen we geen log sturen van het tarief **Non Refundable**.

**Oplossing**
Het is belangrijk dat een overboeking zo snel mogelijk wordt uitgezocht. Wanneer de fout ligt aan de kant van protel heeft het development team namelijk zo veel mogelijk informatie nodig. Hierbij is het noodzakelijk om een screenshot te hebben van het kamertype plan met een zichtbare timestamp (van je laptop, browser of protel zelf). Dit zodat het duidelijk is op welk moment er welke dag overboekt was.
![Room type plan](https://user-images.githubusercontent.com/95683488/146155947-9934e4b4-27cb-45f6-a3e2-0c8bb7d493cf.png)

1. **Controleer de reservering en kijk in het kamertype plan welke dag daadwerkelijk overboekt is.**
2. **Bekijk de reservering in de IDS**
De overboeking komt als een failed reservation binnen (met error **Error: (44) The category is fully booked**). Aan de hand van het bevestiging nummer kun je nakijken waarom het failed binnen is gekomen. Aan de hand van deze check, kun je ook het juiste tarief en kamertype achterhalen, je checkt dit zo:
IDS > Booking History > Aankomst/vertrekdatum invullen > PMS reserveringsnummer of CRS nummer invullen > Refresh
Je kunt ook filteren op failed of succeeded imports bij de dropdown 'Show all entries'
![Booking history](https://user-images.githubusercontent.com/95683488/146155869-7abcafaa-c96d-4f67-b47f-60cd07dc5dd6.png)

3. **Controleer welke beschikbaarheid we stuurden in IDS vóór het tijdstip van de import van de overboeking:**
IDS > Export log files > Exported for (vul je de periode in, waarvoor we data moeten sturen) > Exported between (vul je de periode in, wanneer wij de prijs gestuurd wordt) > je kunt eventueel filteren op kamertype en rate code > voor de beschikbaarheid heb je het tabje 'Availability' nodig > refresh (wacht tot de data geladen wordt en druk niet te vaak op dit knopje)
![Export log files](https://user-images.githubusercontent.com/95683488/146156044-885f8aa2-d6d1-476d-9ef1-2b221b33d75e.png)

4. **Onderneem actie aan de hand van het resultaat.**
Optie 1. Wij hebben een correcte beschikbaarheid gestuurd van 0 --> zet de channel manager in cc en voeg een screenshot toe van wat wij gestuurd hebben.
Optie 2. Wij hebben geen correcte beschikbaarheid gestuurd van 0 --> Controleer waarom dit het geval heeft kunnen zijn.
-- indien het een fout is van het systeem --> maak een [Jira ticket](https://theflowpack.sharepoint.com/:w:/r/_layouts/15/Doc.aspx?sourcedoc=%7BDFC61878-84DB-43FC-9D6F-01298E1EF8A2%7D&file=Checklist%20(trouble%20shooting)%20Jira%20ticket.docx&action=default&mobileredirect=true)
-- indien het geen systeem fout is geweest --> informeer klant dat het een andere oorzaak heeft.
Deze oorzaak kan altijd verschillen, maar kan bijvoorbeeld zijn:
- Twee boekingen die tegelijkertijd gemaakt worden (1 in protel & 1 in OTA)
- Een kamerwissel naar een ander kamertype, die tijdelijk zorgt dat een kamertype beschikbaarheid krijgt.

In het voorbeeld van dit ticket stuurden wij een beschikbaarheid van 1. 
In protel kun je zien dat er op het exact hetzelfde moment een reservering is gemaakt door het hotel:
![Schermafbeelding 2021-12-15 om 10 15 14](https://user-images.githubusercontent.com/95683488/146158564-67c7793f-b39d-4613-a61f-01367863f06d.png)

Om 9:41 is de reservering in protel gemaakt en om 9:42 is de overboeking binnengekomen. Dit is dus geen systeem fout omdat het een aantal minuten duurt voordat de reservering van de OTA naar de CHM naar protel gaat. 
Dit kan meegedeeld worden aan de klant.

**Comment by TomMestrom** [comment]
27-12-21 Tm: ''Wij sturen dan een beschikbaarheid voor kamertype Deluxe en alle verschillende tarieven. Een beschikbaarheid van 0 die bijv. gestuurd wordt voor het kamertype deluxe en het tarief Non Refundable, heeft geen invloed op de beschikbaarheid voor de Fully Flexible'' Zou dit duidelijker kunnen? Misschien uit leggen a.d.v. van een uitgewerkt voorbeeld met kamertype a en tarief a/b 

WV: dit is letterlijk een voorbeeld met kamertype en tarief? Wat is er precies onduidelijk?

**Comment by TomMestrom** [comment]
27-12-21 TM: '*In de IDS is er een export en een import functie, wanneer er data geëxporteerd wordt, kan er geen boeking geïmporteerd worden. Er zijn meerdere mogelijke oorzaken voor een overboeking:'' is dit niet het gevolg van punt 5?

''Op het moment van de overboeking, is er manueel (door een receptioniste) een boeking gemaakt '' hier wordt toch twee keer tegelijk geëxporteerd en geïmporteerd (zou geen hindernis ondervinden, right)?

WV: Wat bedoel je precies? Als er tegelijkertijd een boeking wordt gemaakt in protel en in een van de online kanalen, dan kan protel dit niet op tijd sturen waardoor er een kans is op een overboeking.

**Comment by TomMestrom** [comment]
27-12-21 Tm:

''-- indien het geen systeem fout is geweest --> informeer klant dat het een andere oorzaak heeft.'' Wat is de andere oorzaak?

WV: dan is het een manuele 'fout' (bijv. een boeking die op hetzelfde moment is gemaakt als een online boeking. Dan kan het systeem nooit op tijd die beschikbaarheid sturen)
Maar dat verschilt dus per case, en hangt af van wat er gevonden is in de resultaten.

**Comment by TomMestrom** [comment]
27-12-21 tm: Dit is dus geen systeem fout.
Dit kan meegedeeld worden aan de klant. (Als het geen systeem fout is, wat dan wel?) en wat communiceren we naar de kl ant (mede gedeeld) 

Groetjes Raoul & Tom 

WV: dan communiceren we de oorzaak :)

**Comment by WillemFlow** [comment]
Ik heb wat aanpassingen gemaakt, is het zo duidelijker?
