### ISSUE TITLE
IDS | Wat te doen als reserveringen niet geïmporteerd worden

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#30]
**Oorspronkelijke vraag:**
Reserveringen worden niet geïmporteerd in Protel.

**Oplossing:**
1. Vraag zo veel mogelijk [informatie](https://360.articulate.com/review/content/8b8b172a-5310-4468-9067-ee8128975bc0/review) over de reservering, of om de bevestiging door te sturen, zodat je dit na kan kijken. Denk aan: over welke datum, gast, reserveringsnummer, tarief, etc. het gaat. Makkelijkste is als je om de reserveringsbevestiging vraagt.
2. Ga naar IDS > zoek de reservering op aan de hand van het CRS nummer > check of deze ondertussen wel/niet geïmporteerd is:
![booking history](https://user-images.githubusercontent.com/95683711/147557594-d170a524-acd2-4852-93c2-64e1eab4edbc.png)

Er zijn 3 mogelijke opties:
1. De reservering staat in het groen (de reservering is wel geïmporteerd).
2. De reservering staat in het rood (de reservering is met een bepaalde [oorzaak](https://360.articulate.com/review/content/8b8b172a-5310-4468-9067-ee8128975bc0/review) niet geïmporteerd).
3. De reservering staat er niet tussen.

Oplossingen voor de opties
1. Mogelijk heeft het hotel niet goed gezocht, dit dient nagekeken te worden.
2. Zoek de oorzaak uit en communiceer hoe dit opgelost moet worden naar het hotel (zie [SOP IDS](https://360.articulate.com/review/content/8b8b172a-5310-4468-9067-ee8128975bc0/review)).
3. De reservering is nog niet ontvangen van de channel manager.
Je kunt voor de zekerheid proberen om de reservering nog eens te importeren. Op het hotel druk je met de rechter muisknop om de volgende opties te krijgen:

Je kunt dan 'Start reservation import' of 'Import specific reservation' kiezen.

![Screenshot 2021-12-29 at 12 28 13](https://user-images.githubusercontent.com/95683711/147657879-f4d73216-26da-497d-bf1f-2c50a7ed0c79.png)

![Screenshot 2021-12-29 at 12 28 40](https://user-images.githubusercontent.com/95683711/147657891-04770725-c2c4-467e-a178-445f882cde67.png)

Het is ook mogelijk om via 'import specific reservation het CRS nummer in te voeren en deze specifiek te importeren.
Hier dien je het CRS nummer in te voeren zonder '-1' erachter.
![Screenshot 2021-12-28 at 11 31 23](https://user-images.githubusercontent.com/95683711/147557334-6d182ed1-7ec8-4852-a260-f9d54bc513a3.png)

Als dit niet werkt betekent het dat een van de volgende oorzaken ervoor zorgt dat de boeking niet geïmporteerd wordt:
- Te lange export tijd (Controleer hoe lang de export al draait. Is dit langer dan 1 uur, stop dan de export manueel).
- Storing aan de kant van CHM (vraag eerst aan de channel manager of de reservering al gestuurd is, zo ja vraag om xml).
- Storing aan de kant van Protel (reservering kan niet ontvangen worden --> jira ticket (incl. bovenstaand xml).

Communicatie aan klant: 
1. De klant laten weten dat je het mailtje ontvangen hebt en het issue onderzocht wordt.
- Wanneer de reservering succesvol geïmporteerd is, communiceer dit naar de klant en vraag het om te bevestigen.
- Wanneer het niet lukt, dien je de oorzaak verder uit te zoeken en aan de hand daarvan actie ondernemen.
Eerst vraag vraag je aan de CHM (zet in cc indien ze dat nog niet staan) 'bewijs' dat de reservering gestuurd is (XML). 
Indien ze deze aanleveren --> maak een Jira
Indien ze dit niet gestuurd hebben --> fout ligt bij CHM (afwachten tot ze het opgelost hebben).
- Te lange export tijd > dit ligt vaker aan het hotel en hoe hun tarieven opgebouwd zijn. Controleer of er overlapping tarieven zijn en communiceer dit naar de klant.

Intercom link:
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/2992778/conversations/36000017576
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/unassigned/conversations/36000017788

**Comment by WillemFlow** [comment]
Susy & Willem --> belletje

**Comment by TomMestrom** [comment]
27-12-21 TM RH : ''Vraag zo veel mogelijk informatie over de reservering'' Welke informatie precies? 

29-12 ZW: Zie SOP IDS > Troubleshooting

**Comment by TomMestrom** [comment]
27-12-21 TM RH: De reservering staat in het rood (de reservering is met **een bepaalde oorzaak** niet geïmporteerd). misschien een idee om 'de bepaalde oorzaken' uit te schrijven? 

29-12 ZW: Zie SOP IDS > Troubleshooting

**Comment by raoulhendriks** [comment]
27-12-21 TM RH: 
![image](https://user-images.githubusercontent.com/91269868/147556082-b9923fb4-6983-4aea-b153-09c74166bb91.png)
Ik zou bij de laatste stap, 'vervolgens krijg je hier wel of geen resultaat' ook het nummer voor zetten.
Dus 3. Hier krijg je nu wel of geen resultaat
29-12 ZW: gedaan

**Comment by TomMestrom** [comment]
27-12-21 TM RH:  hebben de ''opties'' allemaal dezelfde oplossingen? 
29-12 ZW: Hoe bedoel je precies? We hebben 3 mogelijkheden/opties beschreven en daaronder de oplossingen.
29-12 @ZsuzsannaWu je hebt 3 mogelijke opties uitgeschreven en daaronder staan 3 oplossingen voor de opties. Maar gelden deze oplossingen voor alle opties? of zijn er oplossingen die specifiek op 1 opties gericht is?
02-01 ZW: natuurlijk hoort bij optie 1 - oplossing 1. Als je de reservering wel ontvangen hebt, hoef je deze bijvoorbeeld dan ook niet opnieuw te importeren.

**Comment by TomMestrom** [comment]
27-12-21 TM RH: Hier dien je het CRS nummer in te voeren zonder '-1' erachter. Misschien een voorbeeld geven? Voor ons is dit vaag
29-12 ZW: klaar

**Comment by TomMestrom** [comment]
Communicatie aan klant:

De klanten laten weten dat het issue onderzocht wordt (afwachten tot ze het opgelost hebben -> proactief zijn) 
29-12 ZW: erbij gezet :)
