### ISSUE TITLE
DRAFT | PMS | Wat te doen als het hotel aangeeft dat er geen lijsten geladen worden in Protel?

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#31]
**Oorspronkelijke vraag:**
Het komt wel eens voor dat hotels bellen/mailen, omdat ze geen lijsten kunnen laden in Protel.

**Oplossing:**
Vaak kan dit worden opgelost met 'Purge Redis Cache'.
Wanneer dit uitgevoerd dient te worden, kan best een Jira ticket aangemaakt worden (en meteen nabellen), of wanneer Sem en Willem werken, kunnen zij dit ook uitvoeren.

**Communicatie aan klant:**
Nadat dit uitgevoerd is, laat het uiteraard altijd weten aan de klant, zodat zij verder kunnen met hun werkzaamheden.

**Comment by WillemFlow** [comment]
algemeen maken voor als er iets 'onverklaarbaars' gebeurd.

En uitleg purge redis cache toevoegen

**Comment by TomMestrom** [comment]
Top comment Willem

**Comment by ZsuzsannaWu** [comment]
weghalen, als iets onverklaarbaars gebeurt, gewoon Jira ticket aanmaken
