### ISSUE TITLE
PMS | Wat te doen als het hotel niet kan printen?

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#32]
**Oorspronkelijke vraag:**
Het hotel geeft aan dat ze niet kunnen printen.
Vraag allereerst (als je de info niet hebt), hoe ze dat precies bedoelen.
- Krijgen ze een error? Zo ja, welke?
- Op welke manier proberen ze te printen?
- Gebeurt dit bij 1 gebruiker of bij meerdere?

**Oplossing:**
Wanneer het een error code betreft, kijk goed naar de melding.
- Het kan aan de templates liggen, in dat geval dienen de templates nagekeken worden. > denk aan JOOscripts 
[Training.templates (2).pdf](https://github.com/renskejetten/CUSTOMER-SUCCESS/files/7799171/Training.templates.2.pdf), maar in sommige gevallen is het template helemaal weg/leeg. In dat geval, kun je best een Jira ticket aanmaken en meteen nabellen.

- Het kan aan de VFS lock files liggen: **Error code:** OfficeException: could not store document: registration_14.pdf caused by IOException: SfxBaseModel::impl_store failed: 0x11b(Error Area:Io Class:Abort Code:27) --> Je kunt hiervoor een Jira ticket aanmaken en Duitsland vragen om de files te verwijderen.

![Screenshot 2021-12-18 at 12 37 27](https://user-images.githubusercontent.com/95683711/146639689-f847c631-a160-4593-a13d-ea6dc769f9e8.png)

1. Ga naar Flash System Data > Support > VFS Browser > juiste map
2. Vervolgens verwijder je de lock files: klik **eerst** op lock registration 14 (pdf bestand) en daarna op 'Löschen'. Schrik niet als het scherm even leeg wordt, de overige files komen binnen enkele seconden terug.
![Screenshot 2021-12-18 at 13 12 42](https://user-images.githubusercontent.com/95683711/146640814-05a75b4f-87ce-4d26-88a2-189e2cb2552e.png)

![vfs](https://user-images.githubusercontent.com/95683711/148686962-42af84aa-5a4f-4059-9069-b91bc20356a4.png)

**Wanneer je dit niet zelf durft te doen, vraag je support collega of maak een Jira ticket aan. Maar het is wel de bedoeling dat wij zo min mogelijk afhankelijk worden van het hoofdkantoor.**

Communicatie aan klant: 
Laat de klant weten, wat je hebt uitgezocht en vraag altijd om te testen of het printen weer naar behoren werkt.

**Comment by TomMestrom** [comment]
27-12-21: ''Het kan aan de VFS lock files liggen: Error code: OfficeException: could not store document: registration_14.pdf caused by IOException: SfxBaseModel::impl_store failed: 0x11b(Error Area:Io Class:Abort Code:27)'' misschien verwijderen? Zou niet iedereen mogen doen.

**Comment by TomMestrom** [comment]
voorbeelden toevoegen van jooscripts (PDF)

**Comment by WillemFlow** [comment]
Ze moeten wel klikken op lock registration 14 en dan op löschen drukken.
Zou ik wel zo specifiek mogelijk er in zetten.

RH 13-1 Waar staat lock regristration 14?

**Comment by TomMestrom** [comment]
06-06-21 Tm: 

'![Uploading Scre' hoort dit tussen de twee screenshots te staan?

**Comment by raoulhendriks** [comment]
13-1 Welke melding krijg je als het aan de templates ligt?

ZW: Dit kan verschillend zijn, ligt er aan wat fout is: replacement code, missende JOOScript, etc.
Goed de foutmelding lezen, meestal staat al hierin wat fout is, dus bij VFS lock files ook.
