### ISSUE TITLE
PMS | Betalingen Verplaatsen

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#34]
**Oorspronkelijke vraag:**
Het hotel geeft aan dat ze geen betaling(en) kunnen verplaatsen.

Wanneer we onvoldoende informatie hebben van het hotel, dienen onderstaande vragen beantwoord te zijn door het hotel:
- Gaat dit om een individuele boeking of een groepsreservering?
- Hebben de reserveringen allemaal dezelfde reserveringsstatus?
- Welke error/foutmelding ontvangen ze bij het uitvoeren van de actie?
- Op welke manier proberen ze de betaling te verplaatsen precies?

https://jira-live.protel.net/servicedesk/customer/portal/232/SUP-8485

https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000016150?q=betaling%20verplaatsen&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Workaround:**
Vaak komt het voor dat betalingen niet verplaatst kunnen worden, omdat de reserveringsstatussen niet gelijk zijn. Bijvoorbeeld: een betaling van een uitgecheckte reservering kan niet verplaatst worden naar een rekening die 'in huis' is.
Wanneer een betaling naar een toekomstige rekening verplaatst moet worden, kan het hotel het beste de opgeboekte betaling tegenboeken en op de toekomstige reservering opnieuw opboeken.

**Communicatie aan klant:**
Beste,

Bedankt voor je mailtje.
﻿Het is niet mogelijk om een betaling te verplaatsen naar een reservering met een andere status.
﻿Als de betaling naar een groepsrekening verplaatst wordt, dienen alle reserveringen in die groep dezelfde status te hebben.
﻿Wanneer er bijvoorbeeld één reservering uitgecheckt is, maar de overige reserveringen nog niet, dan kan de betaling al niet verplaatst worden.
﻿
Ik vertrouw erop je hiermee voldoende op de hoogte te hebben gesteld, maar als er nog vragen of opmerkingen zijn dan hoor ik het graag.
﻿
﻿Met vriendelijke groet,

**Comment by WillemFlow** [comment]
Jira ticket toevoegen
Voorbeeld link toevoegen van een intercom ticket evt?

**Comment by TomMestrom** [comment]
28-12-21 TM RH: dienen de vragen aan het hotel worden gesteld of aan onszelf ?

WV: Als je het zelf niet weet moet je het aan het hotel vragen, dus beide dan

**Comment by TomMestrom** [comment]
28-12-21- TM RH : misschien herformuleren? 

Bedankt voor je mailtje.
﻿Het is niet mogelijk om een betaling te verplaatsen naar een reservering met een andere status.
﻿**Indien** het naar een groepsrekening verplaatst wordt, **dienen** alle reserveringen in die groep dezelfde status te hebben.
﻿**Indien** er bijvoorbeeld één reservering uitgecheckt is, maar de overige reserveringen nog niet, dan kan de betaling al niet verplaatst worden.
﻿
﻿Ik **hoop** dat dit voor verduidelijking zorgt, maar als er nog vragen of opmerkingen zijn dan hoor ik het graag.
﻿
﻿Met vriendelijke groet,
﻿
﻿WV: Wat is hier nu anders aan?
﻿
﻿29-12-21 We hebben het antwoord niet geherformuleerd, alleen aangegeven dat indien, dienen en indien misschien beetje dubbelop is en hierdoor minder fijn leest. Daarnaast 'hopen' wij toch niet? beter vermelden als volgt: ﻿Ik vertrouw erop je hiermee voldoende op de hoogte te hebben gesteld.

02-01 ZW: tekst aangepast.

**Comment by ZsuzsannaWu** [comment]
29-12 ZW: wat stellen jullie anders voor als mailtje?
We hebben tekst toegevoegd bij de vragen.

**Comment by raoulhendriks** [comment]
29-12-21 (doorvragen als je onvoldoende informatie hebt): --> Dit is toch overbodige informatie als je de zin ervoor leest staat er toch al dat als je onvoldoende informatie hebt moet je onderstaande vragen beantwoorden

02-01 ZW: weggehaald, heb ik erbij gezet, omdat je eerst vroeg: 'dienen de vragen aan het hotel worden gesteld of aan onszelf ?'
