### ISSUE TITLE
IDS | Rode Balkjes in Action Monitor IDS

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#35]
**Situatie**
Wanneer je IDS opent, kun je de kolom 'action monitor' tevoorschijn halen, door tussen 'processing state' en connected to / PCI te 'schuiven'.

![Schermafbeelding 2022-02-14 om 14 55 13](https://user-images.githubusercontent.com/95683488/153878145-b7505114-eb0b-4303-abd9-b3837358d619.png)

In de action monitor zijn de eerste twee balkjes van belang.
Als het eerste balkje rood is, betekent dit dat er een error is met het exporteren.
Als het tweede balkje rood is, betekent dit dat er een fout is met de laatste reservering import. Wanneer deze import balk rood is betekent dit niet noodzakelijk dat er een probleem met de koppeling is. Wanneer een klant hier echter over klaagt dient de overboeking uitgezocht te worden om te zien wat de oorzaak is geweest.

Wanneer je ziet dat de export balk rood is, dient dit opgelost te worden.
Je kunt dan op de rechter muisknop klikken, vervolgens 'Log file' > 'Open log file'
![Screenshot 2021-12-18 at 17 06 57](https://user-images.githubusercontent.com/95683711/146648023-e0c1b27d-c049-4731-ad3e-20d3d1336cbd.png)

Daarna ga je zoeken op 'error':
![Screenshot 2021-12-18 at 17 10 12](https://user-images.githubusercontent.com/95683711/146648185-c4155bec-c201-4a9f-b4af-23b338671d62.png)

Aan de hand van de error code ga je actie ondernemen, 
- Als een kamertype niet bij een tarief hoort, uit de matchings verwijderen (zoek op **Code="630"**)
- The protel HTTP server is not available --> jira ticket #28 
- Negatieve prijs. Laat het hotel dit controleren. De error kan voorkomen worden door de volgende optie aan te vinken:
![negatieve prijs](https://user-images.githubusercontent.com/95683488/146787416-d0cc4c9e-3976-4ad6-9928-2025eee0b54d.png)
- Cubilis accepteert het verzoek niet:
2021-02-25 16:16:33 : AE:SendOTAHotelAvailNotifRQ() : **Response** : <?xml version="1.0" encoding="utf-8"?><OTA_HotelAvailNotifRS xmlns="http://www.opentravel.org/OTA/2003/05" Version="2.0"><Errors><Error Code="" ShortText="unknown error" Type="" /></Errors></OTA_HotelAvailNotifRS>

Stuur dit (log file) naar Cubilis en vraag ze waarom ze het niet accepteren. > Nadien moeten we wachten op reactie van Cubilis.
Afhankelijk van het antwoord van Cubilis dienen wij dit verder te onderzoeken, nakijken of communiceren naar de klant.

**Comment by WillemFlow** [comment]
belletje Susy & Willen aanvullen

**Comment by TomMestrom** [comment]
27-12-21: foto toevoegen voor tweede rode balk (Als het tweede balkje rood is, betekent dit dat er een fout is met de laatste reservering import) 

29-12 ZW: gedaan

**Comment by TomMestrom** [comment]
27-12-21: Jip en Janneke taal toevoegen (dummy proof maken)

**Comment by TomMestrom** [comment]
28-12-21 TM: VIDEO is top (misschien naar boven verplaatsen, onder de eerste zin) 
Voordat je uitlegt wat ze betekenen

29-12 ZW: Gedaan

**Comment by TomMestrom** [comment]
28-12-21 TM RH : ''Stuur dit (log file) naar Cubilis en vraag ze waarom ze het niet accepteren.'' is dit de laatste stap of dient dit verder uitgewerkt te worden?

**Comment by ZsuzsannaWu** [comment]
29-12 ZW: Afhankelijk van het antwoord van Cubilis dienen wij dit verder te onderzoeken, nakijken of communiceren naar de klant. > @TomMestrom dit kan altijd een andere oorzaak hebben, dus het antwoord van Cubilis kan verschillen. Dit is veel te veel om uit te werken. We kunnen dit eventueel verder uitwerken als we een recentere voorbeeld hebben.

29-12-21 TM GREAT

**Comment by WillemFlow** [comment]
Als 1 van de 2 balkjes rood is moet je ook kijken
balkje 1 = export
balkje 2 = import (import alleen kijken als de klant er over klaagt)

Dus eigenlijk alleen het eerste balkje
