### ISSUE TITLE
PMS | Vertaling kamerstatus

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#37]
**Vraag:**
Het komt wel eens voor dat de vertalingen van de kamerstatussen niet helemaal correct staan in de PMS.
**Antwoord:**
Deze kunnen wel aangepast/ingesteld worden in de Flash System Data (door Duitsland). Hiervoor open je de configuratie editor > Root > current property > propdata > objectstates
![Screenshot 2021-12-19 at 11 35 56](https://user-images.githubusercontent.com/95683711/146672018-4b173ccd-f5ad-42e6-930f-96a8cde2c027.png)
Als je hier een foutieve vertaling ziet, kun je een Jira ticket aanmaken. #28 
![Screenshot 2021-12-19 at 11 42 44](https://user-images.githubusercontent.com/95683711/146672169-b02ba7c9-d596-4ec5-b54d-3bcb3ddbbdf6.png)

**Comment by WillemFlow** [comment]
aanpassen, moet via Duitsland lopen

**Comment by TomMestrom** [comment]
27-12-21: Jira aanmaken toevoegen
