### ISSUE TITLE
PMS | EOD | Accounting interface error - duplicate guest addresses

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#39]
**Situatie**
Hotels kunnen aangeven dat de gegevens van een dag niet zijn doorgekomen in de accounting software.
Dit kan komen omdat protel het bestand van de back office export niet heeft gestuurd.
Er kunnen meerdere oorzaken en error codes zijn, maar de meest voorkomende is 'duplicate guest addresses'.
De error ziet er als volgt uit (deze krijg je enkel in connect.protel.net):
![Screenshot 2021-12-19 at 13 34 19](https://user-images.githubusercontent.com/95683711/146675153-bc7eccb3-8576-43b9-9017-6c7e4c257118.png)
GenericDestination.Fin.Acc. Error.GenericDestination.BackOffice.revenues are added multiple times to the total sum. (invallid join):com.bao.BaoException: BackOffice - revenues are added multiple times to the total sum. (invallid join):com.bao.BaoException: Fin.Acc. Error - GenericDestination.BackOffice.revenues are added multiple times to the total sum. (invallid join):com.bao.BaoException: BackOffice - revenues are added multiple times to the total sum. (invallid join)

**Oplossing**
Wanneer je deze error ontvangt ga je naar Rapportage > rapporten > duplicate guest addresses > print:

![rapport](https://user-images.githubusercontent.com/95683711/146675780-2913b6c1-104e-46b9-b745-cbde79c93303.png)

Je krijgt dan een lijst met profiel ID's, waarvan dubbele adressen zijn opgeslagen:

![pdf rapport](https://user-images.githubusercontent.com/95683711/146675886-5904e346-cfb3-4dd4-a021-0ad7972e1f4b.png)

Je kunt dan het profiel opzoeken:
![profiel zoeken](https://user-images.githubusercontent.com/95683711/146675908-c15cd228-1c76-4925-b286-f90a68f65f88.png)
![zoeken op profiel nr](https://user-images.githubusercontent.com/95683711/146675913-1ff320e3-afbf-44bc-88d3-09cb72352851.png)

Let wel op dat je in de juiste profielcategorie zoekt, dus privé, bedrijf, travel agent, etc. aanklikken, wanneer je geen resultaat hebt.
![Screenshot 2021-12-19 at 14 04 40](https://user-images.githubusercontent.com/95683711/146675928-a6045551-a908-483d-8a61-055da0ca3ddc.png)

**Het hotel** kan dan één van de adressen verwijderen of bij één adres 'Mailing address' uitvinken:

![Adres](https://user-images.githubusercontent.com/95683711/146675931-074cea97-7af7-4a61-826f-0efd6e43a361.png)

Hoe je het rapport naar Omniboost stuurt/het hotel kan laten sturen, zie:
#40 

Als het dan nog niet goed gestuurd wordt:

Opnieuw EOD rapport aanmaken (#36 ) en jezelf in cc zetten en dan 1 dag afwachten of wij het krijgen.
Krijgen wij het wel --> doorsturen naar Omniboost
Krijgen wij het niet --> Jira (#28 )

**Comment by WillemFlow** [comment]
hotel laten aanpassen (opnemen)

Als het dan nog niet goed gestuurd wordt:
- opnieuw eod rapport aanmaken en jezelf in cc zetten en dan 1 dag afwachten of wij het krijgen.
Krijgen wij het wel --> doorsturen naar omniboost
Krijgen wij het niet --> Jira

**Comment by WillemFlow** [comment]
Opnemen hoe je de data alsnog naar omniboost kan sturen
