### ISSUE TITLE
IFC | Accounting | Missende omzetrapport nasturen

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#40]
**Situatie**
Het hotel geeft aan dat ze dag(en) missen in hun omzetrapportages.

**Oplossing**
Het rapport kan via Rapportage > Rapporten > Export files > Back Office Export uitgedraaid worden. Indien er meerdere dagen missen, moet dit dag voor dag gebeuren.
![back office export](https://user-images.githubusercontent.com/95683711/146677258-1a24c530-c7e1-4dcd-8e3a-58429dc65aa9.png)
Let er op dat je Google Chrome gebruikt. Als je hebt geprint, kun je het bestand versturen naar: vincent@omniboost.io

Draft e-mail naar klant: 

![back office export](https://user-images.githubusercontent.com/95683711/146677395-7bb36c5e-950c-4d2c-9d48-e292dddce55f.png)

Beste,

Bedankt voor je e-mail/telefoon.

De missende data kunnen jullie exporteren vanuit protel Air door onderstaande stappen te volgen:

Hiervoor gaan jullie naar Rapportage > Rapporten > Export files > Back Office Export: back office export

Indien er meerdere dagen missen is het belangrijk dat de back office export dag voor dag wordt geëxporteerd. Hierbij is het belangrijk dat je gebruik maakt van Google Chrome. De gedownloade zip-bestanden kunnen worden verstuurd naar support@omniboost.io met vincent@omniboost.io in CC met het verzoek om deze dag(en) nogmaals door te sturen naar de boekhouding. 

Bij vragen en of opmerkingen hoor ik het graag. 

Voor nu wens ik je nog een fijne dag. 

Met vriendelijke groeten,

**Comment by TomMestrom** [comment]
27-12-21: Downloaden via google chrome -> Zip bestand is toegestaan

**Comment by TomMestrom** [comment]
Beste,

Bedankt voor je e-mail/telefoon.

Wat vervelend om te horen dat niet alle dagen goed geïmporteerd zijn in jullie boekhouding.

De missende data kunnen jullie exporteren vanuit protel Air door onderstaande stappen te volgen:

Hiervoor gaan jullie naar Rapportage > Rapporten > Export files > Back Office Export: back office export

Indien er meerdere dagen missen is het belangrijk dat de back office export dag voor dag wordt geëxporteerd. Hierbij is het belangrijk dat je gebruik maakt van Google Chrome. De gedownloade zip-bestanden kunnen worden verstuurd naar support@omniboost.io met vincent@omniboost.io in CC met het verzoek om deze dag(en) nogmaals door te sturen naar de boekhouding. 

Bij vragen en of opmerkingen hoor ik het graag. 

Voor nu wens ik je nog een fijne dag. 

Met vriendelijke groeten,
