### ISSUE TITLE
PMS | Templates | aanpassingen maken

### ISSUE THREAD

**Issue by WillemFlow** [renskejetten/CUSTOMER-SUCCESS#42]
**Vraag**
Ik wil graag een aanpassing maken aan mijn template, hoe doe ik dit?

**Antwoord**
Beste,

Om de sjablonen te bewerken, dien je te beschikken over het programma OpenOffice. Dit is gratis te downloaden via http://www.openoffice.org/.

Wanneer je OpenOffice hebt geïnstalleerd, kun je via https://app.protel.net/settings/templates/text-templates de sjablonen downloaden. Let even op met openen: waarschijnlijk probeert je computer deze in Word te openen, wat niet de bedoeling is (eenmaal geopend én opgeslagen in Word krijg je het sjabloon niet meer werkend). Kies dus voor “weergeven in map” en vervolgens met de rechtse muisknop “open met” – OpenOffice. Als je OpenOffice als standaardprogramma wilt instellen voor .odt-bestanden, lees je [hier](https://support.microsoft.com/nl-nl/windows/standaardprogramma-s-wijzigen-in-windows-10-e5d82cad-17d1-c53b-3505-f10a32e1894d) hoe dat moet voor Windows en [hier](https://support.apple.com/nl-nl/guide/mac-help/mh35597/mac) voor een MacBook.

Alles wat “gewoon tekst” is, kun je zonder problemen overschrijven of je kunt tekst toevoegen. Meer informatie over codes kun je vinden in de les “Instellingen” in de FLOW University of op de [online help van protel Air](https://help.protelair.com/templates).

Nadat je de sjablonen hebt aangepast, kun je ze weer uploaden op dezelfde plaats als waar je ze hebt gedownload. Ik raad aan om hem onder een nieuwe naam op te slaan i.p.v. een bestaande te overschrijven. Mocht er iets verkeerd zijn gegaan is het natuurlijk wel fijn als je de oude nog als back-up kunt gebruiken.

Voor nog meer informatie over waar templates bewerkt kunnen worden en hoe precies, vind je in de Flow University.

Met vriendelijke groet,

**Overig:**
- Mocht de klant vragen over de JOO scripts dan dient deze een wat uitgebreidere begeleiding te krijgen en kan de volgende informatie gestuurd worden.
Verdere informatie over JOO scripts (de overige dia's gaan over oude protel, kunnen genegeerd worden): 
[Training templates.pdf](https://github.com/renskejetten/CUSTOMER-SUCCESS/files/7788127/Training.templates.pdf)

- Zie hier een filmpje over hoe je het slabloon kan aanpassen in protel.
- 
https://user-images.githubusercontent.com/95683488/147740796-c8896bb6-087c-44bc-85e2-6034b7f31218.mov

**Comment by WillemFlow** [comment]
uitbreiden, JOO scripts

**Comment by TomMestrom** [comment]
27-12-21: wellicht schermopnames toevoegen?

**Comment by raoulhendriks** [comment]
'vind je in de Flow University.' -- Waar vind ik deze informatie?

**Comment by TomMestrom** [comment]
Misschien video toevoegen voor het openen van de sjablonen? 

Nadat je de sjablonen hebt aangepast, kun je ze weer uploaden op dezelfde plaats als waar je ze hebt gedownload. -> waar vind je deze templates?

**Comment by WillemFlow** [comment]
toegevoegd
