### ISSUE TITLE
IFC | Revcontrol | overdue rates found in revcontrol melding

### ISSUE THREAD

**Issue by WillemFlow** [renskejetten/CUSTOMER-SUCCESS#44]
**Vraag**
Mijn Revcontrol account geeft het volgende aan:
'Overdue rates found.
Some rates have not yet been processed by your PMS or CHM.'
Hoe kan ik ervoor zorgen dat de updates wel worden verwerkt?

**Antwoord van Revcontrol**
Wanneer RevControl prijzen doorstuurt naar Protel, sturen wij één of meerdere berichten naar Protel (afhankelijk van het totaal aantal prijzen dat wordt doorgestuurd). Protel zet dan die berichten in een wachtrij om te worden verwerkt. Wanneer deze dan door Protel zijn verwerkt, dan stuurt Protel voor elke bericht een bevestiging door dat de prijzen wel of niet goed zijn verwerkt. Pas op het moment dat alle bevestigingen zijn binnengekomen, kunnen wij pas zeker zijn dat alles verwerkt is (dat wil niet altijd zeggen dat alles is goed gegaan, het kan ook zijn dat Protel dan een foutmelding terug geeft). Tot die tijd is de status van het verzenden van de prijzen "Pending" (wachten op eindresultaat).

Het komt soms wel eens voor dat deze bevestigingberichten niet allemaal bij ons binnen komen. In het geval van Protel, mochten we binnen 15 minuten niet alle bevestigingen binnen hebben gehad, dan waarschuwen we jou via dit bericht. Als je een hotel hebt geselecteerd, dan kun je via https://aeonplaza.revcontrol.com/?module=RevboxReport&command=PublishedRateTimeline zien welke prijzen nog "in de wacht staan". In bijna alle gevallen is het zo, dat de prijzen dan wel al gepubliceerd zijn in Protel, maar dat RevControl gewoon nooit dat bevestigingsbericht heeft ontvangen. Het beste is altijd even dan in Protel te controleren of de prijzen goed zijn binnengekomen.

Mocht dat niet zo zijn, kun je het beste proberen de prijzen opnieuw door te sturen. De waarschuwingen op het dashboard verdwijnen automatisch na 24 uur.

**Link:** [Conversation with Marit Houdijk](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000017607)

**Customer:** [Marit Houdijk](https://app.intercom.com/a/apps/fagrlzth/users/6006ebcd0cd71d02f4be76d8/all-conversations) from [Aeon Plaza Hotels](https://app.intercom.com/a/apps/fagrlzth/companies/613f4d196dd881584aa1babe)
**Customer ID:** 04d13ac8-a11c-4be6-a555-efb534c200da
**Company ID:** 613f4d196dd881584aa1babf-qualification-company
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000017607) when this issue is closed.

**Comment by raoulhendriks** [comment]
Kunnen wij hier vanuit onze kant nog iets checken?
Of loopt dit altijd via Revcontrol

**Comment by raoulhendriks** [comment]
De uitleg hierboven komt vanuit Revcontrol Support, maar als ik deze zo lees. Snap ik er vrij weinig van en zou ik niet precies weten waar ik moet zoeken.

**Comment by WillemFlow** [comment]
Is gewoon een fyi, wij hoeven niks te doen verder

**Comment by raoulhendriks** [comment]
@WillemFlow Okay thanks for the update, dan zetten we hem door
