### ISSUE TITLE
UNI | Aanmaken gebruiker

### ISSUE THREAD

**Issue by raoulhendriks** [renskejetten/CUSTOMER-SUCCESS#45]
**Vraag**

Ik heb een nieuwe werknemer in dienst, kunnen jullie voor hem/haar een nieuw university account aanmaken.
(Check hierbij altijd of je alle gegevens hebt: De naam, het email adres en de functie (medewerker/manager)

**Antwoord**
**GEBRUIKERS MAKEN** 
Ga naar de Sharepoint en open het excel bestand om gebruikers te importeren. Deze vind je onder 
02 Uni --> 01 Flow University --> 03 Intern --> 05 Algemeen --> Gebruikersimport University

Als je dit gedaan hebt kom je op het volgende excel bestand uit.
TIP: sla het Excel bestand op, deze zul je namelijk nog wel vaker nodig hebben.
 
Kies dan vervolgens onderin het tabblad ‘Users’ en vul de gegevens in van de gebruiker die toegevoegd moet worden, Dit doe je voor alle gebruikers!
Login naam: Voor en achternaam aan elkaar
Firstname: Voornaam
Lastname: Achternaam
Email: Email adres
User-Type: Afhankelijk van de functie: Learner-Type (medewerkers) of Admin-Type (managers)
Branch: Naam van het hotel, zoals die in de Uni genoemd is
Course: Hierin vul je alle courses in die deze gebruiker nodig heeft. (Check bij een actieve gebruiker met dezelfde functie in het hotel welke cursussen ze nodig hebben) **LET OP!** Elke course moet in een aparte kolom staan en de naam moet exact hetzelfde als in de Uni zijn.
 
![image](https://user-images.githubusercontent.com/91269868/147462640-f439a2c0-32f8-4949-872e-a22b74fbfbd4.png)

**GEBRUIKERS IMPORTEREN**
Wanneer je alle gebruikers aangemaakt hebt in Excel, ga je terug naar de University naar het kopje import & export (Klik op ‘Ga naar’ en selecteer ‘Import & export’)
Kopieer nu de eerst rij met de hoofdkoppen en plak deze hierin. 
Daarna kopieer je alle gebruikers die je wilt toevoegen en plak deze eronder.
Dit ziet er dan als volgt uit:
 
![image](https://user-images.githubusercontent.com/91269868/147462667-8f53f9b6-69eb-4c5f-88b3-6768efa2b666.png)

Klik vervolgens onderaan op de knop ‘Importeer’ en al je toegevoegde gebruikers zijn nu aangemaakt bij je hotel. Dit kun je controleren door naar het hotel te gaan en op gebruikers te klikken, hier moet nu je aangemaakte gebruiker tevoorschijn komen. Zoals te zien is in onderstaande foto

![image](https://user-images.githubusercontent.com/91269868/147462679-7be4a526-b49f-4a5c-b0a3-3673ccc01a9b.png)

**GEBRUIKERS AANTAL AANPASSEN PIPEDRIVE**

Wanneer je nieuwe gebruikers aanmaakt in de Uni omgeving is het ook altijd belangrijk dat je deze ook aanpast in de Pipedrive deal van het hotel. Wat je hierbij moet doen is het volgende. 
Pas het kopje 'Nr. of users University' aan in de details lijst van het hotel (zie onderstaand)  

![image](https://user-images.githubusercontent.com/91269868/147469735-a7e30626-50c8-4e2a-af0d-5992694d14f2.png)

Wanneer je dit gemaakt hebt ga je ook een finance task aanmaken, deze noem je als volgt ‘Aanpassen uni in EOL & Dealwaarde’. Zet hierbij in de notities alle informatie die nodig is, ‘Nieuwe aantal users (zoals in details) : ‘Totaal nummer gebruiker invullen hier’ en als laatste taak koppel je deze taak aan Tim. Hij zal deze dan controleren. (Zie onderstaande foto als voorbeeld) 

![image](https://user-images.githubusercontent.com/91269868/147469746-1c708498-3872-4ddd-aba3-f8d897c0c395.png)

**GEBRUIKERS CONTROLEREN IN PROTEL IAM**

Nadat je de nieuwe gebruikers aangemaakt hebt in de University en het aantal veranderd hebt in PD. Is er nog een laatste check die je moet doen voordat je klaar bent. Controleer namelijk in protel IAM of er nog actieve accounts in staan die momenteel nog geen University account hebben. 
﻿Alle medewerkers van het hotel die een login hebben voor protel Air dienen namelijk ook de FLOW University te volgen en iedere medewerker krijgt hierbij zijn eigen account. Deze zijn namelijk onlosmakelijk verbonden met elkaar.
﻿
﻿Dit doe je door naar het usermanagement te gaan in protel IAM. Negen blokjes rechtboven in --> IAM --> User management
﻿
﻿Zoek het desbetreffende hotel om te kunnen zien welke account actief of inactief zijn. Vul hierbij het volgende in:
﻿Application: PMS
﻿Level: Hotel
Values: 'Het desbetreffende hotel'

Verander linksonderin de Items per page naar 100, zodra je dit hebt gedaan ziet het er als volgt uit:

![image](https://user-images.githubusercontent.com/91269868/147733564-5e62c58d-2430-4b6b-bc85-ff554b04cace.png)

Wat je nu nog moet doen, is een voor een de accounts te openen (Helaas is hier nog geen snellere manier voor) en te checken of ze actief zijn. Dit is het geval wanneer onderstaand 'schuifje' naar rechts staat:

![image](https://user-images.githubusercontent.com/91269868/147733734-0b9a05ae-7617-44d7-934f-d0a9719786f6.png)

Staat dit schuifje naar rechts, maar heeft deze medewerker nog geen University account. Maak deze dan aan!

**Comment by TomMestrom** [comment]
27-12-21: Pd toevoegen (taakje(s) aanmaken finance & linkerkant bijwerken)

**Comment by TomMestrom** [comment]
28-12-21 TM: wellicht goed idee om te kijken hoeveel gebruikers er zijn in Protel? (daarna kan nog worden bepaald of er extra uni gebruikers moeten worden gemaakt)
