### ISSUE TITLE
Error Credit Card 

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#46]
**Vraag**

Ik mail u met betrekking tot onderstaande foutmelding in Protel.
Helaas hebben wij momenteel geen toegang tot creditcard gegevens. 

![image](https://user-images.githubusercontent.com/72549907/147464562-dbe0fa3e-7c68-4e11-9c62-b15964b03a6e.png)

**Antwoord**

Een jira ticket aanmaken #28 
Voorbeeld jira ticket https://jira-live.protel.net/servicedesk/customer/portal/232/SUP-311210

**Communicatie**
Beste,

Bedankt voor uw mailtje.
We zullen dit nakijken en houden u op de hoogte.

Met vriendelijke groet,

**Communicatie na oplossing**
Beste,

Ik wil u graag op de hoogte stellen dat dit probleem opgelost is.
Ik zie graag je mailtje tevoorschijn komen mocht dit niet het geval zijn.

Voor nu wens ik je nog een fijne dag.

Met vriendelijke groet,

**Link:** [Conversation with reserveringen@bastionhotels.nl](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000017615)

**Comment by TomMestrom** [comment]
''Protel is in ons gebruik een lege shelf en er is geen payment interface aan gekoppeld. Zoals bekend gebruiken we deze PMS enkel voor het ontvangen van de boekingen'' Snap niet goed wat hiermee wordt bedoeld?

**Comment by TomMestrom** [comment]
Wat communiceren we naar de klant?
