### ISSUE TITLE
ICE Lijsten bij outages

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#47]
**Oorspronkelijke vraag:**
app.protel.net werkt niet (storing) en het hotel belt, omdat ze niet verder kunnen (inchecken, uitchecken)

**Workaround:**
Geef het hotel aan dat ze tijdelijk kunnen werken in connect.protel.net. Indien ze geen toegang hebben bieden we aan om een aantal lijsten aan te leveren (ICE = In Case of Emergency).

**Opmerkingen:**
- Facturen kunnen niet geprint worden in connect.protel.net.
- **Nieuwe hotels** hebben geen toegang hebben tot connect en in **andere hotels** hebben niet alle gebruikers toegang tot connect.

De lijsten vind je hier:
![Schermafbeelding 2021-12-30 om 10 41 41](https://user-images.githubusercontent.com/95683488/147740098-26450e88-c6a7-4414-8c32-7d32dbe015fb.png)

In de lijst kunnen er kolommen toegevoegd of weggehaald worden. In overleg met het hotel dien je dit aan te passen zodat de lijst naar wens is voor het hotel.

![Schermafbeelding 2021-12-30 om 10 42 43](https://user-images.githubusercontent.com/95683488/147740224-80ab6ec4-6df0-44a6-8dfe-118ffc12987e.png)

**Communicatie aan klant:** 
Telefonisch contact:
Noteer welk hotel dit betreft en noteer ook het e-mail adres van de contact persoon.
Vraag welke lijsten ze nodig hebben en welke informatie ze daarbij willen (welke kolommen).
- Aankomst
- Vertrek
- Housekeeping
- Gasten in huis

**E-mail:**
Beste,

_'klein stukje over de oorzaak van de outage en de cloudstatus pagina die ze in de gaten kunnen houden'._

Om door te kunnen werken is het mogelijk om via connect.protel.net de ICE lijsten uit te draaien. Indien jullie hier geen toegang tot hebben kunnen wij deze ook voor jullie aanleveren.
We horen dan graag welke lijsten jullie willen ontvangen en welke informatie (kolommen) hier zeker in moeten staan.
De ICE lijsten zijn bijvoorbeeld:
- Aankomst
- Vertrek
- Housekeeping
- Gasten in huis

Onze excuses voor het ongemak en we horen graag welke lijsten we kunnen aanleveren voor jullie, indien jullie het niet zelf kunnen uitdraaien.

Met vriendelijke groet,

**Comment by TomMestrom** [comment]
27-12-21: In overleg met team vervolgstappen uitwerken

**Comment by raoulhendriks** [comment]
'Let er ook op de juiste datum en benodigde kolommen' --> Deze zin loopt niet goed, er mist iets

**Comment by TomMestrom** [comment]
Wat is de volgorde van de stappen die moeten worden genomen in de tweede screenshot? (bijvoorbeeld nummers toevoegen) 

Misschien communicatie aan klant uitbreiden?

**Comment by raoulhendriks** [comment]
Moeten we niet eerst vragen of ze toegang hebben tot connect?
Want anders kunnen ze het gewoon zelf doen toch?

**Comment by WillemFlow** [comment]
Tekst aangepast
