### ISSUE TITLE
PMS | Connect | Match & Merge Profiles

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#49]
**Oorspronkelijke vraag:**
Het hotel vraagt hoe ze profielen kunnen samenvoegen.
Op dit moment is dit alleen in connect mogelijk, Protel Duitsland werkt er aan om deze functie ook beschikbaar te maken in NG(app.protel.net).

Workaround:
Allereerst kun je checken, of jij of de gebruiker die 'Match&Merge' gaat uitvoeren, dit recht ook heeft:
![Profielen menu](https://user-images.githubusercontent.com/95683711/147489475-df52166e-fcd2-427d-90bb-e36ef601c885.png)
Als je onderaan geen 'Match & Merge' / 'Vergelijken & Samenvoegen' ziet, kun je dit recht aan jezelf of een andere gebruiker toewijzen in connect:
![menu](https://user-images.githubusercontent.com/95683711/147490672-ee78a568-c314-4006-9fdd-f696c766e1ba.png)
![user management](https://user-images.githubusercontent.com/95683711/147490675-776f2ae4-11bd-44b6-bb9e-b288e9ccfa2c.png)
![assign role](https://user-images.githubusercontent.com/95683711/147490677-937f6edf-f4c5-421d-bc9e-73804cdfa60f.png)

Vervolgens kun je met cmnd/ctrl + F zoeken naar de naam van het recht:
![recht](https://user-images.githubusercontent.com/95683711/147489710-e315babd-8573-4ff3-ad70-d8a0ebd3383b.png)

Dit document Match & Merge kun je ook doorsturen naar de klant:
https://theflowpack.sharepoint.com/01%20PMS/Forms/AllItems.aspx?id=%2F01%20PMS%2F03%20SUPPORT%2F02%20PROTEL%20AIR%2FSOP%27s%20NG%2Fmatch%20and%20merge%2Epdf&parent=%2F01%20PMS%2F03%20SUPPORT%2F02%20PROTEL%20AIR%2FSOP%27s%20NG

Communicatie aan klant: 
Beste,

In de "nieuwe" protel is het nog niet mogelijk om gastprofielen samen te voegen. Dit kun je nu nog doen in de oude versie. Hier ga je naar toe via de settings rechtsboven. Bij profiles --> match & merge kun je de profielen samenvoegen.
﻿
<img width="188" alt="profielen menu1" src="https://user-images.githubusercontent.com/95683711/147490858-846bd631-8900-4c99-a6b8-7e2feae78971.png">

In de bijlage vind je een SOP over het samenvoegen van de profielen.﻿
﻿Mochten er nog verdere vragen zijn dan hoor ik het graag.

Met vriendelijke groeten,

Intercom link:
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000017699?q=matthieu&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by raoulhendriks** [comment]
De stappen om uit leggen hoe je het recht toevoegt en waar je het vind zijn heel duidelijk.
Maar ik mis nu nog de uitleg hoe we de profielen daadwerkelijk samenvoegen

AA: Die staat hier:
Dit document Match & Merge kun je ook doorsturen naar de klant:
https://theflowpack.sharepoint.com/01%20PMS/Forms/AllItems.aspx?id=%2F01%20PMS%2F03%20SUPPORT%2F02%20PROTEL%20AIR%2FSOP%27s%20NG%2Fmatch%20and%20merge%2Epdf&parent=%2F01%20PMS%2F03%20SUPPORT%2F02%20PROTEL%20AIR%2FSOP%27s%20NG

**Comment by TomMestrom** [comment]
Communicatie aan klant -> willen wij dit zo communiceren naar de klant? ''ik durf echter niet te zeggen wanneer precies' ik denk dat het intensie van het bericht moet zijn dat het nog kan in de oude omgeving

WV: weggehaald
