### ISSUE TITLE
PMS | Wijzigen BTW tarief 

### ISSUE THREAD

**Issue by TomMestrom** [renskejetten/CUSTOMER-SUCCESS#50]
Belastingen zijn variabel en kunnen van tijd tot tijd veranderen. Deze handleiding zal u tonen waarmee u rekening moet houden bij het aanpassen van uw belastingtarieven, zodat alles vlot kan verlopen.

Als uw land bijvoorbeeld besluit zijn BTW-tarief te wijzigen, moet het nieuwe BTW-tarief in protel Air opnieuw worden aangemaakt en moeten de belaste artikelen op de vastgestelde datum aan het nieuwe BTW-tarief worden aangepast.

Het nieuwe belastingtarief kan reeds op voorhand worden vastgesteld. **De toewijzing van het nieuwe belastingtarief kan echter pas worden uitgevoerd op de datum waarop de belasting in werking treedt.**

**1.	Creëer nieuwe belastingtarieven**

•	Open de protel Air SYSTEM DATA (Apps menu ⇾ System Data).
•	Klik in het navigatiemenu op **Financiële configuratie ⇾ Belastingen**.
•	Nadat het venster **Belastingen** is geopend, klikt u op de knop **+NIEUW** om een nieuw belastingtarief aan te maken.
•	Maak in het dialoogvenster **Belasting toevoegen** het nieuwe belastingtarief aan zoals in de volgende afbeelding.

**OPMERKING:**
1.	De waarden in de figuur zijn slechts voorbeeldwaarden. Vervang de voorbeeldwaarden door uw eigen waarden.
2.	Zorg ervoor dat u het selectievakje **Gedetailleerde factuur**
selecteert.

<img width="155" alt="image" src="https://user-images.githubusercontent.com/95683473/147551185-f4338ba0-0b97-4d45-ac5a-ccf8477e7382.png">

•	Bevestig het belastingtarief door te klikken op het Opslaan icoon	en vervolgens het venster te sluiten.

**2.	Voer een test-bemiddeling uit**

U kunt een testboeking uitvoeren enkele dagen voordat de eigenlijke BTW-wijziging plaatsvindt - nadat u het nieuwe belastingtarief hebt aangemaakt en voordat u het nieuwe belastingtarief aan al uw artikelen toekent op de dag dat het nieuwe belastingtarief van kracht wordt. 

**Voorbeeld**

1.	Maak een testfactuur en post een testartikel op deze factuur.
2.	Wijs het nieuwe belastingtarief toe aan het test-item.
3.	Voer de eind van de dag routine uit.
4.	Post daarna het test-item op dezelfde factuur.
5.	Sluit de rekening.

De factuur moet nu beide artikelen bevatten, elk met een verschillend BTW-tarief.

**3.	Wijs nieuw belastingtarief toe**

Het tijdstip waarop de artikelen worden geboekt en niet het tijdstip van facturering is absoluut doorslaggevend voor de toepassing van het nieuwe belastingtarief. Daarom is het belangrijk voor elk artikel een datum voor de wijziging van de belasting over de toegevoegde waarde vast te stellen.
Deze datum is de datum waarop de nieuwe belasting over de toegevoegde waarde voor al uw artikelen van kracht wordt.

**Praktisch voorbeeld**

In de veronderstelling dat het nieuwe belastingtarief op 01 oktober van kracht wordt, zouden de belastingtarieven voor alle posten in de nacht van deze belangrijke datum naar het nieuwe belastingtarief worden overgeschakeld. U zou dus de einde-dagroutine zoals gebruikelijk uitvoeren in de nacht van 30 september op 01 oktober (datum waarop het nieuwe belastingtarief van kracht wordt). Alle Items zouden geboekt worden met het oude belastingtarief voor 30 september. Na de einde dag routine zal het nieuwe belastingtarief aan alle items worden toegekend. Dit moet beslist gebeuren vóór het uitvoeren van de eerste boeking op de afgesproken dag (01 oktober)!

**OPMERKING:** U kunt een testfactuur maken voordat u de bovenstaande wijzigingen uitvoert voor alle artikelen op de vastgestelde datum (zie stap 2 hierboven).

**Dit is wat je moet doen**

Open de protel Air SYSTEM DATA (Apps menu ⇾ System Data).

Open de systeemgegevens van de posten door in het navigatiemenu te kiezen voor **Financiële configuratie ⇾ Posten ⇾ Posten.**
 
Verwerk elke post waar het belastingtarief verandert, als volgt.

Als u uw artikelen in productgroepen hebt georganiseerd, opent u elk artikel één voor één en brengt u de volgende wijzigingen aan in de artikelen:

1.	Selecteer het betreffende item en klik op **Bewerken.**
2.	Selecteer het nieuwe belastingtarief in het venster **Item bewerken.** **OPMERKING:** De waarde in de figuur is slechts een voorbeeldwaarde. Vervang de voorbeeldwaarde door het belastingtarief dat voor uw situatie van toepassing is.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/95683473/147551529-03602b2b-bb40-4cf7-aef2-c4f284d6f409.png">

3.	Klik boven in het venster op het pictogram Opslaan.
4.	Herhaal stap 1-3 voor elk artikel in uw systeem waarvoor u het belastingtarief moet aanpassen.

Nadat u ze hebt opgeslagen, worden de artikelen in kwestie met het nieuwe belastingtarief geboekt.

**4.	Tariefupdates**

Nadat u de BTW-tarieven voor al uw artikelen hebt aangepast, moet u ervoor zorgen dat beide belastingtarieven worden berekend voor gasten wiens verblijf samenvalt met de datum waarop het nieuwe belastingtarief wordt toegepast: Tot één dag voor de vastgestelde datum (bijv. 30 sept.) is.
 
het oude belastingtarief de basis voor de berekening; vanaf de vastgestelde datum (bijv. 01. okt.) is het nieuwe belastingtarief de basis voor de berekening.

Om dit te doen kunt u de reserveringslijst voor de aangewezen datum oproepen en eerst de kamerprijzen voor alle reserveringen "vergrendelen" met de optie **Bedrag logies vergrendelen.** Zo voorkomt u dat de kamerprijs wordt overschreven als er tussentijds wijzigingen worden aangebracht.

Na de datum waarop het nieuwe belastingtarief wordt toegepast, is het mogelijk dat er nog reserveringen in het systeem zijn die nog het oude belastingtarief hanteren. Daarom moet u de tarieven voor toekomstige reserveringen bijwerken met de functie Tarieven **bijwerken.**

Voorbeeld

1.	Ga naar de reserveringslijst voor de vastgestelde datum - bijv. 01 oktober (Receptie
>Reservaties).
2.	Klik op **BULK.**
3.	Selecteer alle reserveringen.
BELANGRIJK! Let op het aantal reserveringen dat in de lijst wordt weergegeven! Als niet alle reserveringen worden weergegeven, moet u de weergave uitbreiden door op de pijl naar rechts te klikken die zich helemaal onderaan het scherm bevindt!
4.	Klik op de knop **Bedrag logies reserveren** - zie de volgende schermafbeelding.

![image](https://user-images.githubusercontent.com/95683473/147551677-09a39ef2-1b4e-4c65-a92d-09b73cc40f23.jpeg)

5.	Heropen de reserveringslijst opnieuw, dit keer voor één jaar in de toekomst, bijvoorbeeld van 01 oktober 21 tot 01 oktober 22.
6.	Herhaal de stappen 2 en 3 en klik op de knop **Tarieven bijwerken.**

Geregeld. Alle reserveringen zijn bijgewerkt met het nieuwe belastingtarief.

**Comment by ZsuzsannaWu** [comment]
09-01 ZW: dit gaat enkel over BTW's
City tax werkt iets anders, dus dat zou ik uit het titel halen en apart uitwerken (nieuwe shotgun wel) :)
