### ISSUE TITLE
FOUTMELDINGEN | 500, 502, 504 ETC 

### ISSUE THREAD

**Issue by TomMestrom** [renskejetten/CUSTOMER-SUCCESS#51]
**500**

Een Failed request geeft aan dat de server het door de client verzonden verzoek niet kon verwerken vanwege een ongeldige syntaxis. Net als bij de tientallen mogelijke HTTP-responscodes kan het zowel frustrerend als lastig zijn om een Bad Request Error te ontvangen bij het openen van uw eigen applicatie. Dergelijke HTTP-responscodes vertegenwoordigen de complexe relatie tussen de client, een webapplicatie, een webserver en vaak meerdere webservices van derden, dus het bepalen van de oorzaak van een bepaalde statuscode kan moeilijk zijn, zelfs binnen een gecontroleerde ontwikkelomgeving.

<img width="232" alt="image" src="https://user-images.githubusercontent.com/95683473/147553826-4268e05f-5287-4089-907f-0b81595edd3d.png">

**502** 
De 502 foutmelding is een status code zoals andere http error codes. Daarmee geeft de server aan dat er iets fout loopt bij het verkrijgen van de gevraagde content op een bepaalde webpagina. Wanneer je deze error blijft krijgen, probeer dan de rechten van de user opnieuw te assignen, dit kan het probleem oplossen

![image](https://user-images.githubusercontent.com/95683473/147554054-1fc9c783-3f30-4655-890b-c62203e673bb.jpeg)

**504**
Timeout (60 seconden moeten wachten) 

De 504 Gateway Timeout fout is één van de meest voorkomende HTTP 5xx fouten die websitebeheerders en bezoekers zien. Aangezien de 504 Gateway Timeout error niet vermeldt wat de oorzaak van de fout is, kan het lastig zijn om de precieze reden van de servertime-out te achterhalen. 

<img width="232" alt="image" src="https://user-images.githubusercontent.com/95683473/147553853-0b93fe5a-6259-4e1e-8240-9547e3a46dee.png">

**Comment by raoulhendriks** [comment]
Moet hier misschien wat meer uitleg bij, wat de errors inhouden en wat je er tegen kunt doen?
