### ISSUE TITLE
IDS | Tarieven koppelen 

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#52]
**Vraag**

Je ontvangt een mail van een klant om een tarief te koppelen.
Hoe koppel je een tarief?
A: Is het Cubilis?
B: is het Smarthotel/Siteminder?

**Antwoord**

**A: Cubilis**

**Stap 1:** 
Zorg ervoor dat je altijd een protel ID - Cubilis ID ontvangt van de klant.
Voorbeeld protel ID 93 - Cubilis ID 69904. 
Het Protel ID kan je altijd terugvinden door te gaan naar systemdata - tarieven - tariefcodes.

<img width="1670" alt="Schermafbeelding 2021-12-28 om 11 39 23" src="https://user-images.githubusercontent.com/72549907/147558163-4fd370c9-6b7b-4f4f-9339-0ceddb00a0b5.png">

**Stap 2:**

Ga naar simba: https://simba.protel.net/?l=customerAdmin&action =HotelID
Log in en zoek het betreffende hotel.
Klik op "Launch protel AIr"

<img width="1675" alt="Schermafbeelding 2021-12-28 om 12 33 18" src="https://user-images.githubusercontent.com/72549907/147562175-a43276ba-100e-4418-a545-98308334af89.png">

Kopieer de link in de balk naast URL.
https://simba.protel.net/?l=customerAdmin&customer=46101

<img width="560" alt="Schermafbeelding 2021-12-28 om 11 00 12" src="https://user-images.githubusercontent.com/72549907/147554445-226a3e58-032d-4e33-85de-f334d6eaafb0.png">

**Stap 3:**

Klik op Go en log in met je simba gegevens.
Klik nu links onder op Support en dan Configuration Editor 

![configurator F1](https://user-images.githubusercontent.com/72549907/147554768-2678d514-441b-42bb-9b51-285e18ad5507.png)

Nu moet je een aantal mapjes gaan uitvouwen 

Root --> currentProperty --> propData --> Interfaces --> ProtIDS --> 'Instance ID' --> Klik op Matchings

![confi F2](https://user-images.githubusercontent.com/72549907/147554965-0a61a330-139c-4c34-9d4a-f6014ec0b2e2.png)

![conf F3](https://user-images.githubusercontent.com/72549907/147554996-58456118-358c-4622-92f3-fb12b06a2b8c.png)

Koppel je protel ID met je Cubilis ID:

![matching 2](https://user-images.githubusercontent.com/72549907/147559449-79ea5826-156c-444b-9704-98a57a91a524.png)

 klik op ‘Änderungen speichern’ rechts onder en vervolgens op ‘Commit’ links onder.

**B: Smarthotel/Siteminder**

Bij Smarthotel/Siteminder dient er niet gekoppeld te worden met een Cubilis ID (cijfers) maar wordt er gekoppeld met een naam of letters. Deze worden aangeleverd door klant evenals aan welk kamertype deze dienen gemapt worden. Overige stappen dienen hetzelfde gevolgd worden.

![conf  smarthotel](https://user-images.githubusercontent.com/72549907/147754024-761175d8-8746-483d-9da0-ddf68ae69b5c.png)

**Stap 4:**

Ga naar Protel ID starter.

![Schermafbeelding 2021-12-28 om 11 28 34](https://user-images.githubusercontent.com/72549907/147557031-38a08a72-cadb-4b6c-ab0f-e7124994e9fb.png)

Zoek het betreffende hotel en dubbel klik:

![Schermafbeelding 2021-12-28 om 11 59 51](https://user-images.githubusercontent.com/72549907/147559600-ab74387f-9e43-48da-b257-9cdee446c762.png)

Bij PMS settings kan je controleren of deze goed zijn gekoppeld.

![Schermafbeelding 2021-12-28 om 11 35 26](https://user-images.githubusercontent.com/72549907/147559872-9beb0051-8a85-4e3a-aa4d-ca6d8e52063f.png)

Vervolgens ga je naar External Inventory (als het tarief hier niet tussen staat dan staat het niet correct in Cubilis. Geef het hotel aan dat dit nog niet correct staat ingesteld).
Bij SIteminder/Smarthotel is er **geen External Inventory**. Hiervoor dienen hotels aan te geven welk kamertype dit gekoppeld dient te worden.

![external inventory](https://user-images.githubusercontent.com/95683711/148933198-0e49a7f8-28b5-40a9-b955-413de1ff8b8b.png)

Je zoekt welke kamertype bij je nieuwe tarief code hoort en noteer dit.
![external inventory codes](https://user-images.githubusercontent.com/95683711/148933223-46b0cf48-d836-4cec-a468-913808c45a33.png)

**Stap 5:**

**A: Cubilis**
Ga naar Export - Channel matching Pairs:
Klik rechts onder op Add combinations:

![Schermafbeelding 2021-12-28 om 12 17 49](https://user-images.githubusercontent.com/72549907/147561212-2e45f82b-47ac-472a-a10a-9f9ecc0f1c0f.png)

Selecteer je kamertype dat je hebt genoteerd bij je tarief code:

![Schermafbeelding 2021-12-28 om 12 19 13](https://user-images.githubusercontent.com/72549907/147561331-73e59ad7-4ee1-4866-8717-1289cfb66d3a.png)

Selecteer je tarief code. Klik rechts boven op Add en nadien op OK.

Laat het hotel controleren of de geexporteerde informatie in de Channel Manager correct is. En controleer of deze correct binnen komt in de PMS.

**Comment by TomMestrom** [comment]
Top gedaan audrey!
