### ISSUE TITLE
PMS | Connect | Policies

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#53]
**Vraag:**
Hoe/waar stel je verschillende aanbetalings-/ annuleringsvoorwaarden in?

**Antwoord:**
Op dit moment is dit enkel in connect.protel.net in te stellen. Het is wel de bedoeling dat deze functies ook in app.protel.net beschikbaar worden.

Hiervoor log je dus in op connect.protel.net, vervolgens ga je naar system data > reserveringen > voorwaarden

![voorwaarden](https://user-images.githubusercontent.com/95683711/147565447-d4f25be5-1466-4fef-a019-36a3037767a0.png)

Als je op voorwaarden hebt geklikt, zie je aan de linkerkant verschillende menu's om voorwaarden aan te maken/bewerken.
Met het knopje 'add' kun je een nieuwe voorwaarde aanmaken. Als je een bestaande voorwaarde wilt bewerken, kun je op de voorwaarde dubbel klikken, zodat het menu opent.
Het hotel geeft zelf aan met welke garantie-of annuleringsvoorwaarden ze willen werken. Hiernaar vul je ook de gegevens in.
![deposit policies toevoegen](https://user-images.githubusercontent.com/95683711/147565654-2d24c822-b802-4539-8475-2251f39ec391.png)
![deposit policies instellen](https://user-images.githubusercontent.com/95683711/147565660-b9371f63-22af-4016-93e5-cd27e2fd1d30.png)
![cancellation policy instellen](https://user-images.githubusercontent.com/95683711/147565822-18577ec9-a4e0-4d30-87c2-feeed87aafc1.png)

Voordat je voorwaarden voor groepen kunt aanmaken, dien je eerst 'individuele' voorwaarden aan te maken.

Als je de voorwaarden succesvol hebt aangemaakt, kun je ze aan je tariefcodes (waar de voorwaarde moet gelden) aanhangen. Dus ga je naar 'rate assignment' en klik je naast de rates in het dropown-menu de juiste voorwaarde aan.
![policies aan rate codes hangen](https://user-images.githubusercontent.com/95683711/147565899-fd80cd79-7739-43ae-a6ae-0d3f4be0c377.png)

Mochten klanten problemen hebben met een (oudere reserverings)bevestiging, nadat ze hun voorwaarden hebben aangepast, dienen zij eerst in de reservering het tarief te updaten.
![Screenshot 2021-12-28 at 13 28 05](https://user-images.githubusercontent.com/95683711/147566356-2289c6d8-0a53-42ef-86cc-39ae93ca242f.png)

Intercom link:
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/2992778/conversations/36000017638

**Comment by raoulhendriks** [comment]
Ik zou het koppelen van de voorwaardes aan de rates ook even uitschrijven inplaats van alleen een foto

02-01 ZW: Heb dit aangepast in de tekst, maar het koppelen is gewoon de juiste voorwaarde aanklikken bij de rate. Geen rocket science ;)

**Comment by TomMestrom** [comment]
Wat dient er ingevuld te worden in de screenshots? 

02-01 ZW: Heb dit aangepast in de tekst, maar het hotel geeft dit natuurlijk zelf aan (percentage, dagen, etc.) het spreekt ook voor zich.
