### ISSUE TITLE
EOD | Gebruiker toevoegen bij betalingsoverzicht

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#54]
**Vraag**

Hoe kan ik gebruikers toevoegen in mijn betalingsoverzicht? 

**Antwoord**

Hiervoor ga je naar dagafsluiting - rapportage en lijsten.
Je gaat naar "betaallijsten" en klikt op de 3 bolletjes.
Kies voor bewerken.

<img width="1675" alt="Schermafbeelding 2021-12-28 om 13 53 20" src="https://user-images.githubusercontent.com/72549907/147568692-9d755d40-4f38-4c56-bbe8-5753c731bf89.png">

Vervolgens ga je naar "gebruikers". Klik je op het drop down menu.
Je selecteert je gebruiker.
Als de gebruiker er niet tussen staat kan het zijn dat diegene nog niet heeft ingelogd.
Dit dient eerst te gebeuren alvorens deze in de dagafsluiting rapportage naar voren komt.

<img width="997" alt="Schermafbeelding 2021-12-28 om 13 51 57" src="https://user-images.githubusercontent.com/72549907/147568720-500608e1-1c69-4b6e-beda-c8d8505cae55.png">

**Comment by AudreyAdamus** [comment]
AA; Tekst dient nog wat aangepast te worden

**Comment by raoulhendriks** [comment]
Misschien toevoegen dat die gebruiker wel al eens heeft moeten inloggen in protel

WV: aangepast :)

**Comment by raoulhendriks** [comment]
![image](https://user-images.githubusercontent.com/91269868/147669399-85e59c8f-bb88-413a-bbbe-edc4183e21ba.png)

Als ik naar dagafsluiting ga bij ons FLOW Support account, zie ik de betaallijst niet erbij staan.
Moet deze niet eerst worden aangemaakt? zoja even uitleggen hoe

WV: Als iemand geen betaallijst heeft ga ik er van uit dat diegene deze vraag ook niet stelt :)
