### ISSUE TITLE
IFC | POS | Koppeling ligt er uit, what to check?

### ISSUE THREAD

**Issue by WillemFlow** [renskejetten/CUSTOMER-SUCCESS#56]
De kassa koppeling werkt niet en het hotel belt dat ze niet kunnen doorboeken.
Voor de volgende stappen in volgorde uit:

1. Vraag of ze een error krijgen in de kassa met het doorboeken. Noteer deze error voor het geval we een Jira ticket moeten maken. 
2. Check of de pCon verbinding heeft:
Ga naar Simba en zoek het hotel op. Klik op IFC --> Launch Interface Configuration:
![open interface](https://user-images.githubusercontent.com/95683488/147675666-6d8fa0de-4fe1-40e7-bb6c-d1e3289d34e7.png)

Rechtsonder zie je het volgende:
![image](https://user-images.githubusercontent.com/95683488/147675812-7c81a5eb-e454-4b91-9e5f-563fa25ff8e1.png)

-Als de onderste 'stekker' grijs is ligt het aan de pCon: Het is mogelijk dat de computer waar de pCon op geïnstalleerd is niet aan staat. Dit kun je controleren met het hotel. Als dit het geval is dient de computer aangezet te worden. Als de computer wel aan staat ga je naar stap 7.
-Als de bovenste 'stekker' grijs is heeft dit te maken met POS (kassa) : Hier moet de server van de POS herstart worden (Hiervoor dient het hotel zelf contact op te nemen met de kassa leverancier).

3. Herstart de interface:
![image](https://user-images.githubusercontent.com/95683488/147675888-a04c8708-63cb-4da5-b019-e6490070ca03.png)

Druk op 'deactivate ifc' en vervolgens weer op 'activate ifc'

4. Controleer 'view orders'
![image](https://user-images.githubusercontent.com/95683488/147676067-efb46eb4-66c2-444d-ba29-5481a59dc392.png)

Wanneer dit geen 0 is, betekent dit dat er bonnetjes vastlopen en dat minstens één bonnetje een foutmelding genereert.
Pas wanneer die foutmelding opgelost is, kunnen er weer bonnetjes doorkomen. Het is dus noodzakelijk dat dit zo snel mogelijk gebeurt. 
Controleer de foutmelding in het envelopje links van de pCon (zie stap 2)

De foutmelding kan bijvoorbeeld zijn:
subject: PosXml.xxxx
message: The TAA **xxx** assigned for a POS posting with PG **xxxxx**, TX 1, OL 1, SF 1 does not exist. Please assign another TAA or create it as soon as possible because ALL further POS postings are blocked until this problem has been solved.

Dit betekent dat de Productgroep (PG) uit de kassa niet gekoppeld is met een artikel uit protel, en daarom niet geïmporteerd kan worden. Deze dient dan zo snel mogelijk gekoppeld te worden. In de praktijk zie je dit niet vaak, gezien we altijd een 'onbekend' artikel koppelen die als fallback artikel werkt.

5. Controleer in protel of er geen “rare” tekens staan in de namen van reserveringen of groepsreserveringen (bijvoorbeeld: Å of Æ) Dit kan de koppeling namelijk niet vertalen, wat ervoor zorgt dat er niks geboekt kan worden van de kassa naar protel.

6. Als dit allen niet het geval is, controleer met de kassa leverancier of het IP adres en het poortnummer nog overeenkomen.
Dit is het host IP van de pCon:
![Schermafbeelding 2021-12-29 om 16 22 44](https://user-images.githubusercontent.com/95683488/147677284-a8b8bbc7-1d42-491b-bcab-2014d4bd1219.png)

Dit IP moet ook altijd bij de kassa ingevoerd zijn.
Dit kan wijzigen als het hotel geen statisch IP heeft ingesteld.

Het poortnummer veranderd over het algemeen niet, maar kun je voor de zekerheid aan de kassaleverancier aanleveren:
![Schermafbeelding 2021-12-29 om 16 32 07](https://user-images.githubusercontent.com/95683488/147678190-5cbe5f02-ca55-48df-90fa-270b06066a93.png)

7. Als dit niet werkt log je in via teamviewer op de computer van het hotel waar de pCon op geïnstalleerd is.
Hier kan de pCon gedeactiveerd worden en opnieuw geïnstalleerd worden:
[PAir_pCon_Install_en.pdf](https://github.com/renskejetten/CUSTOMER-SUCCESS/files/7789598/PAir_pCon_Install_en.pdf)
Zie blz. 21 & 22 voor installeren en deïnstalleren van de pCon.

Controleer in de map van de pCon of het de laatste versie is (er staat dan dat het van 25 feb. 2020 is).
Als dat niet het geval is, gebruik de laatste versie:
https://s3.eu-central-1.amazonaws.com/protel-cloud/public-files/ifc/ifc.html
 
 8. Als het hierna nog niet werkt, maak een Jira ticket met alle informatie uit bovenstaande stappen. Hierbij voeg je de info uit de log van de pCon toe (download pCon.log op de computer van de klant).

**Comment by AudreyAdamus** [comment]
<img width="1276" alt="Schermafbeelding 2022-08-08 om 09 58 12" src="https://user-images.githubusercontent.com/72549907/183368895-3eb7b82a-4bc6-46a4-b909-005c38a64d5e.png">

1. Go in to Simba >> Select the hotel >> Right click >>  Select IP config.
You will see the IP address is missing here.

<img width="1336" alt="Schermafbeelding 2022-08-08 om 10 01 05" src="https://user-images.githubusercontent.com/72549907/183369438-af4f155d-a4d6-41a0-a6a3-c76a640f2874.png">

2. Go to overview tab >> Select Purge Redis Cache >> Click yes
This will clear the server or API connection error (if there are any)

<img width="1221" alt="Schermafbeelding 2022-08-08 om 10 04 07" src="https://user-images.githubusercontent.com/72549907/183369988-8199afbf-55f1-4cd2-8084-38286abec4dd.png">

3. Go to Licensing Tab >> From the affected IFC, click start interface

<img width="1516" alt="Schermafbeelding 2022-08-08 om 10 06 11" src="https://user-images.githubusercontent.com/72549907/183370233-9581040e-19b5-43ff-9949-a4d37642129b.png">

4. Repeat Step 1 ... this time you will see the IP address

<img width="1062" alt="Schermafbeelding 2022-08-08 om 10 08 31" src="https://user-images.githubusercontent.com/72549907/183370637-6791dacd-b7a4-461f-9942-f8c3df85eecf.png">

5. Right click >> IFC Control >> View Orders

Thiis to check and confirm after if anything are stuck on the IFC
