### ISSUE TITLE
PMS | Dezelfde lijst in de groepsreservering geeft bij verschillende users verschillende resultaten

### ISSUE THREAD

**Issue by sembierings** [renskejetten/CUSTOMER-SUCCESS#58]
**Originele vraag:**
_Wij ondervinden verschillen in weergave van reserveringsaantallen naargelang de gebruiker.
Hoe kunnen we dit aanpassen aub._
**Link:** [Conversation with Raphael van Nevel](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000017486)

**Antwoord:**
![Schermafbeelding 2021-12-30 om 11 20 21](https://user-images.githubusercontent.com/95683579/147744307-01df4954-1fbf-4137-8811-13ccb3061545.png)
![Schermafbeelding 2021-12-30 om 11 20 40](https://user-images.githubusercontent.com/95683579/147744316-f878e4c4-47b2-4eff-be8a-ad268698b8ad.png)
![Schermafbeelding 2021-12-30 om 11 20 59](https://user-images.githubusercontent.com/95683579/147744325-817b0760-f213-4801-855a-e407a76cc208.png)
![Schermafbeelding 2021-12-30 om 11 21 21](https://user-images.githubusercontent.com/95683579/147744330-87fd706a-1faa-4f34-a7a5-6755032d5776.png)
![Schermafbeelding 2021-12-30 om 11 22 00](https://user-images.githubusercontent.com/95683579/147744334-8fb485e7-ab0f-4d9e-baf4-7854a1ad1eeb.png)
![Schermafbeelding 2021-12-30 om 11 22 36](https://user-images.githubusercontent.com/95683579/147744369-7a8b5ceb-0257-4ddf-9f61-4911308957c0.png)

**Comment by raoulhendriks** [comment]
Uitleg is duidelijk voor mij.

Weet alleen niet of ik het zo fijn vind om alle rode blokken en tekst in de screenshots te hebben.
