### ISSUE TITLE
DRAFT | PMS | Posting text --> Duplicate

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#60]
**Vraag:** 
Klanten kunnen de volgende vragen stellen: 
- Dubbel omzet geboekt (lijkt zo door de verschillende regels op de factuur)
- Nu lijkt het er op dat er 3 prijzen worden geboekt, echter na verrekening klopt deze prijs wel.
- etc.

**Antwoord:**
Kijk de reservering en de factuur goed na. Als je hier niks vreemds ziet (manuele boekingen door medewerkers, etc), kun je in system data het tarief controleren. 
Als je op de factuur twee regels met verschillende 'packages' ziet, kun je bijna zeker van zijn, dat dit om de posting teksten gaat.

- kijk het tarief na:
![Screenshot 2022-01-12 at 10 35 04](https://user-images.githubusercontent.com/95683711/149109122-95eebd7c-7dde-48a9-8ad6-52d3ffd626c8.png)

Kijk de tarief berekeningen na:
![Screenshot 2022-01-12 at 10 54 50](https://user-images.githubusercontent.com/95683711/149117677-b2c8aa6d-4fd5-419a-8b35-cf0775a8ef51.png)

Stel hier de posting tekst voor het difference item in.

Als je *split package* selecteert, wordt het difference item als een afzonderlijk artikel geboekt. (BELANGRIJK: Op de gastenfactuur staan ​​dan ook tariefwijzigingen die optreden als gevolg van een tariefstrategie of iets dergelijks, dus tariefverhogingen!)
Selecteer *Maak nieuw aan* om een ​​nieuwe posting tekst in te voeren (bijv. "Off-Season-pakket"). Je kunt ook een bestaande tekst selecteren in de vervolgkeuzelijst.

**Als het difference item samen met de accommodatie en andere inbegrepen diensten/artikelen moet worden geboekt, voer dan dezelfde posting tekst in voor het difference item en alle andere delen van het tarief. Alle artikelen en toeslagen worden vervolgens gecombineerd in één factuurregel.**

**_Als je dus verschillende posting teksten hebt geselecteerd in het tarief en in de berekening, komen deze dus ook als aparte regels op de gastenfactuur._**

Je ziet het eigenlijk al aan de factuur, dat er twee verschillende regels geboekt zijn voor één overnachting. Op één regel wordt er omzet geboekt, op de andere wordt het verschil (dat aangepast is) tegengeboekt.

Als het inderdaad aan de posting text ligt, kun je onderstaand bericht naar de klant sturen: 

Beste,

Bedankt voor je mailtje.

Dat je verschillende posting texts/ boeking teksten op de rekening ziet, komt waarschijnlijk door dat de dagelijkse details (prijzen) aangepast zijn in de reservering, Protel boekt dan het verschil in het bedrag op de posting text/ boeking tekst tegen.

Het is ook een mogelijkheid, wanneer er bijvoorbeeld een restrictie van +€20 is ingesteld, boekt Protel dit op het tarief en niet op de berekening.

Ik zal hieronder een uitleg geven:

Boeking tekst tarief verschilt van boeking text tarief berekening:
![posting text tarief](https://user-images.githubusercontent.com/95683711/147879779-55f2f66d-321c-445b-8d4b-342e283c3cc0.png)
![posting text berekening](https://user-images.githubusercontent.com/95683711/147879790-e0cab769-4f70-4530-b83f-094218a7c487.png)

Reservering gemaakt, hierbij heb ik de daily details/dagelijkse details nog niet aangepast, zie 'originele rekening' onder de foto van de reservering:
![reservering en knopje daily details](https://user-images.githubusercontent.com/95683711/147879812-60f9676f-1cb8-41a9-b5eb-ff427502aaf6.png)
![factuur origineel - voor aanpassing daily details](https://user-images.githubusercontent.com/95683711/147879827-c51bae5a-426f-44fe-9972-173fc890b25f.png)

Vervolgens heb ik de prijs aangepast:
![daily details (prijs) reservering](https://user-images.githubusercontent.com/95683711/147879847-eac691e2-f23d-42f0-b9b1-43d7c7e3d218.png)

Waardoor de factuur dan als volgt uitziet:
![tegenboeken op tarief posting text](https://user-images.githubusercontent.com/95683711/147879861-12cf5ca9-db4d-4716-8365-15b0fe36e7c1.png)

De oplossing voor de verwarring is dus een boeking tekst selecteren, die overeen komt met de tekst van de berekeningen, dus in het tarief zelf en in de berekeningen dezelfde posting tekst gebruiken, bijvoorbeeld 'Flow arrangement' als we naar mijn voorbeeld kijken.

Ik hoop dat dit zo duidelijker is voor je, mocht je hierover nog vragen hebben, vernemen we graag van je.

Met vriendelijke groeten,

Intercom link: https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000017414?q=posting%20text&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by TomMestrom** [comment]
11-01-22TM 

''Kijk de reservering en de factuur goed na. Als je hier niks vreemds ziet, kun je in system data het tarief controleren. Als het inderdaad aan de posting text ligt, kun je onderstaand bericht naar de klant sturen''

Wanneer wordt iets als niks vreemd ondervonden? 

Misschien handig om een filmpje te maken? Voor mij is dit namelijk namelijk echt lastig te volgen.

**Comment by WillemFlow** [comment]
Eerst uitleggen hoe het werkt in de instellingen.
Daarna uitleggen op welke plekken in de reservering dit van toepassing kan zijn.

Nu lijkt het alsof alles om daily details draait terwijl dat maar een onderdeel is van

Dus meer inzoomen op de instellingen en welke posting text waar effect heeft

**Comment by ZsuzsannaWu** [comment]
ik verwijs jullie graag naar draft 2
