### ISSUE TITLE
PAIR | Reservering kan niet geannuleerd worden

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#61]
**Vraag**

Ik kan mijn reservatie niet annuleren.

**Dit kan twee redenen hebben**

**Antwoord Reden 1**

Controleer altijd als er kosten/betalingen zijn geboekt. Hiervoor ga je naar je reservatie - factuur. Wanneer er kosten zijn geboekt wordt dit in het zwart getoond.
Check als er een MLOS in deze reservering zit. Zo ja, dan dien je deze stappen ook te volgen #71 

![Schermafbeelding 2022-01-03 om 11 31 23](https://user-images.githubusercontent.com/72549907/147922261-a45c8603-add2-4ad0-8ec8-ede5ca6e2daa.png)

Zorg dat je balans op je factuur op 0 staat.

![Schermafbeelding 2022-01-03 om 12 12 37](https://user-images.githubusercontent.com/72549907/147924409-7d58c6c2-2d8c-428a-a0e2-5c76d96971a2.png)

Sluit je factuur je af, ook als het balans op 0 staat.

**Communicatie klant**

Beste,

Bedankt voor je mailtje. We hebben dit voor je nagekeken en zien dat er kosten zijn geboekt op de factuur.
Deze kosten dienen tegengeboekt te worden zodat je balans op 0 is. 
Vervolgens dien je ook je factuur te sluiten.

Indien er nog vragen zijn, verneem ik deze graag van je.

Met vriendelijke groeten,

**Antwoord Reden 2**

De reservering is onderdeel van een groepboeking. Deze groepsboeking heeft al kosten/betalingen opgeboekt.

﻿Je kunt het beste deze reservering uit de groep halen. Vervolgens zou je deze moeten kunnen annuleren.

Onderstaand een aantal screenshots:

![image](https://user-images.githubusercontent.com/91269868/159258193-14f47560-7c96-4f25-96ba-ffb4f09cb194.png)

Vervolgens kies je je juiste reservering om uit de groep te verwijderen

![image](https://user-images.githubusercontent.com/91269868/159258213-f12d0358-1c61-4bd3-8ff5-adb612207ee2.png)

Wanneer deze uit de groep is verwijderd, kan deze reservatie worden geannuleerd.

**Communicatie klant**

Beste 

Bedankt voor je mailtje.

﻿Er is momenteel een probleem waarbij de omzet op de groepsfactuur effect heeft op de annulering van de individuele reserveringen.
﻿Je kunt het beste deze reservering uit de groep halen. Vervolgens zou je deze moeten kunnen annuleren.
﻿(Eventueel stappen hierboven meenemen)
﻿
﻿Wanneer deze uit de groep is verwijderd, kan deze reservatie worden geannuleerd.
﻿
﻿We zullen je op de hoogte houden van de status van dit probleem.
﻿Onze excuses voor het ongemak.

Met vriendelijke groeten,

**Comment by AudreyAdamus** [comment]
AA: nog nabootsen en foto's toevoegen

**Comment by raoulhendriks** [comment]
Moeten we uitleggen hoe we tegenboeken?

**Comment by raoulhendriks** [comment]
Is dit de enige reden waarom ze een reservering niet kunnen annuleren?

**Comment by TomMestrom** [comment]
Goede feedback Raoul.

**Comment by AudreyAdamus** [comment]
@raoulhendriks @TomMestrom Ook omwille van een MLOS, daar heb ik een aparte github van gemaakt. Misschien dat ik dit dan ergens kan vermelden met de link

**Comment by raoulhendriks** [comment]
Even toevoegen mbt groepsreservering
