### ISSUE TITLE
pAir | User-defined list

### ISSUE THREAD

**Issue by TomMestrom** [renskejetten/CUSTOMER-SUCCESS#63]
Door elke lijst die u opent in het menu Rapportage ⇾ Lijsten een andere naam te geven, kunnen ze worden opgeslagen als een afzonderlijke lijst. U kunt willekeurige instellingen maken in een lijst, en deze vervolgens opslaan als een nieuwe lijst in het systeem - hetzij alleen voor uzelf of voor alle gebruikers van het hotel. 

De volgende eigenschappen kunnen worden geconfigureerd en opgeslagen: Filterinstellingen, kolomvolgorde, kolombreedte, kolomsortering, kolommen tonen en verbergen (zie ook: Kolominstellingen in lijsten en tabellen).

Hoe gaat u te werk:

1. Open de gewenste lijst via het menu Rapportage ⇾ Lijsten en pas alle instellingen aan uw wensen aan. 

2. Klik op het tandwiel in de rechterbovenhoek van het scherm en selecteer Opslaan als.

<img width="321" alt="Schermafbeelding 2022-01-06 om 09 48 05" src="https://user-images.githubusercontent.com/95683473/148356205-d6ae46b1-63ba-4b06-924f-ae3fc4dfc730.png">

3. Er wordt dan een nieuw venster geopend:

<img width="364" alt="Schermafbeelding 2022-01-06 om 09 49 13" src="https://user-images.githubusercontent.com/95683473/148355702-3043b9bf-82b0-4808-8faa-e0f85a694518.png">

4. Geef de nieuwe lijst een betekenisvolle naam.

5. Kies indien nodig een nieuwe waarde voor de sorteervolgorde. Als de lijst bijvoorbeeld op de eerste plaats moet verschijnen onder "Door gebruiker gedefinieerde lijsten", moet u 1 gebruiken. Als u de lijst in alfabetische volgorde wilt sorteren, laat u de sorteerwaarde leeg.

6. Selecteer of de nieuwe lijst alleen voor u of voor alle gebruikers moet worden opgeslagen. "Alleen voor mij" betekent dat alleen u toegang heeft tot de lijst. "Voor alle gebruikers" betekent dat de lijst ook beschikbaar is voor andere protel Air gebruikers, met uitzondering van de volgende regel: 

**LET OP:** Als uw huidige ingelogde gebruiker een bestaande "Alleen voor mij" opgeslagen heeft, zullen instellingen gemaakt in de "Voor alle gebruikers" opslaan geen invloed hebben op uw lijstweergave. (Lijst voor iedereen is niet mogelijk als individueel is aangepast) 

7. Klik op Opslaan. De lijstweergave wordt dan opgeslagen als een door de gebruiker gedefinieerde lijst. 

8. Om toegang te krijgen tot de opgeslagen lijst, klikt u op de knop Rapportage ⇾ Lijsten in de menubalk, en selecteert u vervolgens ''Eigen lijst''. Al uw door de gebruiker gedefinieerde lijsten staan daar in een lijst.

![image](https://user-images.githubusercontent.com/91269868/149300761-0f904eca-5251-49c9-ac0d-52a6b5e3593c.png)

**Comment by raoulhendriks** [comment]
Lijkt mij in orde zo
