### ISSUE TITLE
PMS | Trainingsversie updaten

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#67]
**Situatie**
Het hotel meldt een issue die je graag wilt testen, maar dit kan niet in de live-versie. 
Je vraagt dan om toestemming van het hotel, of je hun trainingsversie mag updaten. Wanneer je toestemming hebt, kun je de trainingsversie updaten.

**Updaten doe je zo:**
Log in in Simba > zoek het juiste hotel en selecteer de trainingsversie:
![Screenshot 2022-01-09 at 12 27 46](https://user-images.githubusercontent.com/95683711/148680458-17d0c11b-4b14-4fcc-864b-03b618308641.png)
Vervolgens scrol je naar beneden en klik je op 'Copy database from other DB':
![Screenshot 2022-01-09 at 12 27 55](https://user-images.githubusercontent.com/95683711/148680491-f82343ff-214f-4afe-85ff-066aa4bd0dd2.png)
Je krijgt dan een scherm, waarbij een aantal opties aangevinkt zijn:
![Screenshot 2022-01-09 at 12 28 06](https://user-images.githubusercontent.com/95683711/148680508-714a55e8-0523-43a1-865c-a8a911c523d7.png)
**Let op, dat je nog een paar aanpassingen doet, voordat je op 'Start import drukt':**
- Vink de 4e, 6e en 7e vinkjes **UIT**
- Selecteer bij Virtual File/System : Overwrite from: **Source database**

![Screenshot 2022-01-09 at 12 28 17](https://user-images.githubusercontent.com/95683711/148680528-1a16d48b-346b-4a53-b213-c94b11886a52.png)

Wanneer je de gemarkeerde aanpassingen hebt uitgevoerd, kun je op 'Start import' klikken, waarna de import van de live versie zal starten. Dit kan wel even duren, afhankelijk van wanneer de training is geüpdatet en het aantal reserveringen.

Wacht totdat de update helemaal klaar is, anders krijg je een foutmelding (kan geen kwaad), wanneer je de trainingsversie opent.

**Comment by raoulhendriks** [comment]
Staat de sourcedata base altijd automatisch op de live versie?

ZW: Ja, dat is altijd automatisch

**Comment by raoulhendriks** [comment]
Toevoegen dat het afhankelijk van de grote en aantal reservering langer kan duren
ZW: done

**Comment by raoulhendriks** [comment]
Je krijgt hier soms ook een time-out error door toch?
Misschien even erbij zetten en aangeven dat dit geen kwaad kan
ZW: en done
