### ISSUE TITLE
PMS | Factuurnummers aanpassen

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#68]
**Oorspronkelijke vraag:**
Het hotel wilt graag de factuurnummering aanpassen. Ze vragen hoe en waar ze dit kunnen instellen.
Er moet wel op gelet worden dat het eerstvolgende nummer hoger dient te zijn dan het laatst gebruikte nummer in Protel.
Je kunt dit checken, door op 'save' te drukken bij de configuratie, waarna je een foutmelding krijgt als het nummer lager is dan het laatst gebruikte nummer:
![Screenshot 2022-01-10 at 14 27 23](https://user-images.githubusercontent.com/95683711/148773877-aa37ffb9-0dbd-420d-a311-6c10b02e612f.png)

De nieuwe nummering gaat in bij de eerstvolgende factuur.

**Communicatie aan klant:** 

Beste,

Bedankt voor je mailtje. Dit kan je manueel aanpassen. Ik heb hieronder een printscreen toegevoegd.

Hiervoor ga je naar systemdata - financiële configuratie - factuurinstellingen - factuurconfiguratie.

<img width="1652" alt="Factuur" src="https://user-images.githubusercontent.com/95683711/148683987-d3328d28-a41f-4936-98c1-1230d82b7736.png">

Als er nog vragen zijn, dan hoor ik het graag van je.

Ik wens je nog een fijne dag.

Met vriendelijke groeten,

**Intercom link:**
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000017745?q=factuurnummer%20aanpassen&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by raoulhendriks** [comment]
Waar kan ik zien wat het laatste factuur nummer is? Zodat ik bij de het nieuwe nummer een hoger getal heb?

ZW: aangepast :)
