### ISSUE TITLE
IAM rechten aanpassen voor een user

### ISSUE THREAD

**Issue by WillemFlow** [renskejetten/CUSTOMER-SUCCESS#69]
**Vraag**

Een manager van een hotel geeft aan dat een medewerker een functie in het system wel of niet kan gebruiken, maar dit niet zou moeten.
Bijvoorbeeld:
_Mijn werknemer kan niet op rekening afslaan, hoe kan dit?_

**Antwoord**
Beste,

Je kunt in **IAM** bepalen welke rechten bepaalde medewerkers hebben.
In het _Usermanagement_ tabje kun je zien welke werknemers welke rol hebben.
In het _Rolemanagement_ tabje kun je zien welke rechten een bepaalde rol heeft.

![Schermafbeelding 2022-01-10 om 11 37 05](https://user-images.githubusercontent.com/95683488/148752408-f46b7d0d-fc19-408d-9b26-7157c8922811.png)

![Schermafbeelding 2022-01-10 om 11 28 04](https://user-images.githubusercontent.com/95683488/148751209-b54875d4-5086-40b6-bfac-56675038f6bc.png)

In _User management_ kun je een specifieke werknemer opzoeken en bekijken welke rechten deze heeft door het profiel te openen.

![Schermafbeelding 2022-01-10 om 11 29 27](https://user-images.githubusercontent.com/95683488/148751398-8ff4e86f-9531-4aa1-a6fe-f83bfc9100de.png)

De rollen kunnen bekeken worden in _Role management_

![Schermafbeelding 2022-01-10 om 11 30 39](https://user-images.githubusercontent.com/95683488/148751560-9ae78811-2306-4c3c-81a0-8bd592fc5405.png)

Druk op _edit_ om de rol te openen.
In de rol zijn de rechten zichtbaar, waarbij rechts de toegekende rechten zijn en links de nog beschikbare rechten.
Bij een eventuele wijziging kan het recht naar de andere kant worden gesleept.

![Schermafbeelding 2022-01-10 om 11 33 32](https://user-images.githubusercontent.com/95683488/148751858-71e30103-82a0-46d8-9b3c-ca04f9b4206e.png)

De uitleg van de rollen kunnen gevonden worden via de volgende link:
https://protelair.helpjuice.com/roll-permissions-en

Mocht je nog vragen hebben m.b.t. de verschillende rollen helpen we je graag verder. 

Nadat de wijziging is uitgevoerd zal de rol automatisch worden geüpdatet voor alle medewerkers die de rol reeds toegekend hebben gekregen.

Indien er nog vragen zijn, horen we het altijd graag!

Met vriendelijke groet,

**Comment by raoulhendriks** [comment]
Mij lijkt deze uitleg vrij duidelijk
