### ISSUE TITLE
PMS | Hoe een reservering inkorten.

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#71]
**Vraag**

Het lukt mij niet om mijn reservering in te korten. Hoe kan dit?

**Oplossing**

De oorzaak hiervan is de raterulenotvalid foutmelding (zie https://github.com/renskejetten/CUSTOMER-SUCCESS/issues/70)

﻿Het inkorten zou moeten lukken, mits het tarief geen minimum length of stay (MLOS) heeft.
Wanneer een tarief een MLOS heeft dienen de volgende stappen uitgevoerd te worden:

Je opent je tarief:

![Schermafbeelding 2022-01-10 om 09 59 15](https://user-images.githubusercontent.com/72549907/148740646-97e23583-ee9b-49ae-ad36-deff0169d2b4.png)

Je past je lengte voor verblijf aan:

![Schermafbeelding 2022-01-10 om 09 54 33](https://user-images.githubusercontent.com/72549907/148740696-70b0b741-ebc8-4e6f-bd29-f9dca57170f6.png)

Je gaat terug naar je reservering en update je tarief:

![Schermafbeelding 2022-01-10 om 09 56 10](https://user-images.githubusercontent.com/72549907/148740722-76cbfd55-c036-47e2-940d-bd039944aaf6.png)

Je past je datum aan en vervolgens check je deze gast uit:

![Schermafbeelding 2022-01-10 om 09 56 37](https://user-images.githubusercontent.com/72549907/148740773-e83e5d05-2880-4096-a836-9fb48f818909.png)

﻿Vergeet dan niet om het tarief weer terug aan te passen met je MLOS.

**Best ook controleren of er restricties aanwezig zijn.**

![Schermafbeelding 2022-01-10 om 09 54 51](https://user-images.githubusercontent.com/72549907/148743600-dac29bc2-789d-433c-88b2-889d75083f7d.png)

**Comment by TomMestrom** [comment]
11-01-22 TM: Wellicht de stappen uitschijven (nu gaan we van screenshot naar screenshot)
