### ISSUE TITLE
PMS | Protel account dient zelf aangemaakt te worden --> Macro intercom

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#72]
**Vraag**

Ik wil graag een protel account aanvragen.

**Antwoord**

Bedankt voor je bericht!﻿﻿

Een nieuwe gebruiker aanmaken voor Protel kunnen jullie als hotel zelf doen. Alle medewerkers met IAM rechten zijn hiertoe bevoegd. Binnen jullie hotel zijn dit de volgende medewerkers:﻿

- (Opzoeken wie IAM rechten heeft)

Wij kunnen daarentegen wel een account aanmaken voor de FLOW University. Wij hebben dan onderstaande gegevens nodig van de nieuwe medewerker:

- De voor en achternaam
- Het email adres
- De functie (Manager/Medewerker)

Indien er nog onduidelijkheden of verdere vragen zijn, horen we dit altijd graag!

﻿﻿Met vriendelijke groeten,

**Comment by raoulhendriks** [comment]
Moeten we uitleggen hoe en waar ze dit doen?

**Comment by TomMestrom** [comment]
11-01-22 TM: Is dit niet meer een macro i.p.v. een GitHub issue?

**Comment by raoulhendriks** [comment]
Hier is al een macro van, kunnen we sluiten in Github
