### ISSUE TITLE
IDS | Wat te doen als we prijzen niet correct sturen

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#73]
**Vraag**
Het hotel geeft aan dat er verkeerde prijzen getoond worden in de CHM/OTA's.

**Oplossing**
Het is belangrijk dat je weet waar het probleem zit. Zit het probleem tussen de PMS en de CHM of tussen de CHM en de OTA? Vraag om specifieke informatie bij het hotel: 

- Welk tarief en kamertype geven een foute prijs weer?
- Waar en wanneer wordt deze foute prijs weergegeven?
- Wat dient de juiste prijs te zijn en wat is de prijs in protel?

_Fout tussen PMS en CHM_ 
Controleer de prijs in de daily rates (bij een virtueel tarief bij de res enquiry). Dat is de prijs die de IDS overneemt.

![Screenshot 2022-01-10 at 15 53 11](https://user-images.githubusercontent.com/95683711/148786458-081514c9-b2af-4f34-bfab-2c7f5fc0bc73.png)

Als de prijs niet overeenkomt met de prijs die het hotel heeft aangegeven --> laat dit het hotel weten en vraag ze om het te corrigeren.
Als deze prijs overeenkomt met de prijs die het hotel wil sturen --> controleer wat wij sturen:
#25 

Indien we het correct sturen (probleem ligt waarschijnlijk tussen CHM en OTA):
Zet de channel manager in CC en lever ze een screenshot aan van de informatie die wij sturen met de vraag of ze het kunnen controleren. Stuur voor de zekerheid een full update.

Indien we het niet correct sturen:
Zoek uit waarom we dit niet correct sturen.

**Wat kun je controleren?**
- is het tarief juist gekoppeld in de IDS? Controleer of het tarief het juiste ID heeft en of de juiste kamertypes gekoppeld zijn in de chm pairs.
- is de standard occupancy goed ingevuld in de chm pairs? > Wanneer er 0 staat bij de occupancy neemt de IDS de default occupancy van het kamertype in protel over. Het is mogelijk dat dat niet goed ingevuld staat en er een andere prijs gestuurd wordt (bijv. de eenpersoonsbezetting).
- Maintenance > check pAir rates = Controleer of de IDS de juiste prijs herkent van protel.

Check pAir rates doe je zo:
![check pair rates](https://user-images.githubusercontent.com/95683711/148799755-4f6dab40-a42d-41cc-ae1f-41bb926258fe.png)

Hiervan kun je dan aflezen welke prijs door de IDS herkend wordt.
Je kunt bij room type en rate code de ID's invullen die je nodig hebt, deze vind je terug bij PMS Settings:

![rate code id](https://user-images.githubusercontent.com/95683711/148799954-a02fbfa3-e899-4562-8216-1b4f9b50de88.png)

Indien er een andere prijs staat dan in de daily rates, dienen de 'revision numbers' gereset te worden:
#76 

**Intercom link voorbeelden:**
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/5007297/conversations/36000018041 > Best Western (niet in IDS nakijken, maar bij daily rates) 

Voor BWI gelden andere stappen. Lees hiervoor: #55  & #82

**Comment by TomMestrom** [comment]
''Stuur voor de zekerheid een full update'' Misschien bedoeld Susy Full Push?

**Comment by TomMestrom** [comment]
''Als de prijs niet overeenkomt met de prijs die het hotel heeft aangegeven --> laat dit het hotel weten en vraag ze om het te corrigeren.'' Hoe kunnen ze het dan corrigeren? 

Deze stap zou het hotel zelf toch ook op voorhand kunnen doen?
