### ISSUE TITLE
PMS | BWI | CRS Managed profiles

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#75]
**Situatie:** Klanten kunnen bellen/mailen met de vraag, waarom ze profielen niet kunnen bewerken. Meestal gaat dit om Best Western Hotels. De reden dat de profielen niet aangepast kunnen worden is dat de Best Western Interface (indien het in user defined staat aangevinkt: CRS managed) de wijzigingen altijd zal overschrijven naar wat in Memberweb staat.
![CRS managed](https://user-images.githubusercontent.com/95683711/149660751-daa7d0b0-0459-4721-8d88-f026fca815cc.png)

**Oplossing** is dus om de profiel wijzigingen in Memberweb te bewerken. De gast dient dit zelf te doen!
Een locked profile, die ook CRS managed profile is kun je unlocken en bewerken in Protel, maar je wijzigingen zullen altijd overschreven worden door de Best Western Interface.

**Intercom link:** https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/all/conversations/36000017844

**Comment by raoulhendriks** [comment]
Wij kunnen deze toch niet wijzigen? 
Dit moet de gast toch zelf doen

ZW: bij oplossing staat: profiel wijzigingen in Memberweb bewerken, het hotel kan ook in Memberweb.

RH 26-1: Ja dat weet ik, maar kunnen wij of het hotel zomaar een profiel veranderen in Memberweb? Is dit niet alleen iets wat de gast zelf kan doen?

ZW yes, aangepast :)

**Comment by raoulhendriks** [comment]
Misschien handig om uit te leggen hoe het zit met het slotje in het profiel?
Het slotje heeft hier geen zin, want wijzigingen bij een CRS managed profile zullen altijd overgeschreven worden door de BW interface

RH 26-1: Je kunt het slotje wel uitzetten en dan dingen veranderen. Maar zodra er dan een update met het profiel gestuurd wordt veranderd het weer terug. Dat is toch het geval?
Misschien toch handig om aan te geven, anders denken hotels dat het daarmee aangepast kan worden

ZW yes dank je, gedaan :)

**Comment by TomMestrom** [comment]
''Oplossing is dus om de profiel wijzigingen in Memberweb te bewerken.'' Ik neem aan dat wij nooit zelf de profielen van gasten veranderen en dat de klant dit zelf moet doen?

of wordt dit aan de klant gecommuniceerd? 

RH: dit zei ik ook al inderdaad

ZW: Communiceren inderdaad. Wij mogen sws geen aanpassingen doen in live versie van klanten
