### ISSUE TITLE
IDS | Reset revision numbers

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#76]
**Hoe reset je revision numbers in IDS?**
De IDS stuurt informatie op basis van revision nummers.
Elke dag en prijs/kamertype combinatie hebben een revision nummer.
Bij elke wijziging in protel, veranderd het revision nummer. Op deze manier weet de IDS wanneer er een wijziging is en wanneer er dus informatie naar de channel manager gestuurd moet worden.

Het is mogelijk dat revision nummers niet meer oplopen of er bijvoorbeeld een synchronisatie probleem tussen de IDS en PMS is. Het is dan mogelijk om deze te resetten. Dit doe je als volgt:

1. Zet de calculation mode op PMS
![Schermafbeelding 2022-02-01 om 10 29 52](https://user-images.githubusercontent.com/95683488/151944437-8c342575-619e-4b35-898c-e5fd96d5b0d6.png)

2. Deactiveer de instance
![Screenshot 2022-01-16 at 14 26 07](https://user-images.githubusercontent.com/95683711/149661875-f0bb9ade-12dc-474d-8685-0e26eb413d2f.png)

3. Activeer de instance
![Screenshot 2022-01-16 at 14 29 02](https://user-images.githubusercontent.com/95683711/149661981-6f8f9f82-416b-4428-9bed-003ff117d4e4.png)

4. Start full data export
![Screenshot 2022-01-16 at 14 29 45](https://user-images.githubusercontent.com/95683711/149662017-89a3acd6-2c50-4875-9332-c0260d4202e3.png)

5. Zet de status weer terug naar het originele nadat de update klaar is (normaliter is dit 'mixed' (Use NRC for correct configured rates, all others will be requested from protel Air))

**Comment by WillemFlow** [comment]
De lange export en reset revision nummers heeft niks met elkaar te maken.
Dus dat deel mag je weghalen samen met de export annuleren.

Gewoon alleen hoe je het reset.

Reden dat het nodig is, is bijvoorbeeld als er een verkeerde prijs verzonden wordt.

ZW done, dank je wel :)

**Comment by WillemFlow** [comment]
en vergeet niet om m daarna weer op de oude status te zetten :)

**Comment by raoulhendriks** [comment]
Kan er misschien iets meer uitleg bij over wat dit precies doet?
Ik zou nu namelijk de stappen volgen zonder enig idee te hebben wat het precies doet/inhoud

**Comment by raoulhendriks** [comment]
Misschien ook wat meer uitleg wanneer we dit doen?
''Reden dat dit nodig is, is bijvoorbeeld als er een verkeerde prijs verzonden wordt'' 

Wanneer weet ik dan nu dat als er een verkeerde prijs verzonden wordt dat ik dit proces moet starten
![Screenshot 2022-01-19 at 10 03 33](https://user-images.githubusercontent.com/95683711/150098875-1bcf9746-d6d3-4402-8293-efc0a2682d73.png)

**Comment by raoulhendriks** [comment]
Komt deze vraag vanuit een klant? zo ja wat communiceren we?

ZW: heb het erbij gezet, maar dit doe je dus als prijzen/beschikbaarheid na de eerste 2 'opties' niet goed doorkomen.

**Comment by TomMestrom** [comment]
@raoulhendriks is het voor jou nu meer duidelijk n.a.v. de aanpassingen?

**Comment by TomMestrom** [comment]
hoort stap 3t/m 7 niet onder één optie (stap 3) 
ZW ik zie wat je bedoelt, ik heb het aangepast.

**Comment by TomMestrom** [comment]
'' Wanneer er iets niet helemaal lekker loopt wordt er verzocht voor een full push.'' Wordt met iets prijzen en beschikbaarheid bedoeld?
ZW yes helemaal correct

**Comment by raoulhendriks** [comment]
Dus als ik het goed begrijp en het hotel zegt de prijzen kloppen niet
Gaan we eerst een full push doen en zodra dit niet werkt.
Starten we het proces voor reset revision numbers?

Zie ik het zo goed?

ZW: yes, je kunt specifiek een data push sturen voor een bepaalde tarief > bij PMS settings > rate code > rate code markeren voor data export > ok > rechter muisknop op instance > start data export (maar dit is een ander onderwerp)
je kunt een full push doen 
of reset revision numbers

**Comment by TomMestrom** [comment]
wat is een rivison nummer?
![Screenshot 2022-01-19 at 10 03 33](https://user-images.githubusercontent.com/95683711/150098875-1bcf9746-d6d3-4402-8293-efc0a2682d73.png)

**Comment by TomMestrom** [comment]
Hoe doen we een full push? 

ZW rechter muisknop op de instance en dan start full data export, staat ook omgekaderd :) (stap 4)

**Comment by WillemFlow** [comment]
@raoulhendriks aangepast 

@WillemFlow Thanks voor het aanpassen, voor mij is het duidelijk nu!
Heb alleen bij de laatste zin achter 'Mixed' nog even de volledige naam neer gezet om verwarring te voorkomen
