### ISSUE TITLE
Wat te doen als het hotel geen e-mails ontvangt van protel

### ISSUE THREAD

**Issue by WillemFlow** [renskejetten/CUSTOMER-SUCCESS#77]
Wanneer een hotel aangeeft dat ze geen e-mails ontvangen van protel kan dit om twee type e-mails gaan.
- De e-mails die de IDS verstuurt (bijvoorbeeld failed imports of errors)

![Schermafbeelding 2022-01-24 om 12 11 03](https://user-images.githubusercontent.com/95683488/150772624-836655db-325f-42f0-90c9-7850c0714d67.png)

- De e-mails die protel verstuurt naar het de gasten met het hotel in CC (factuur of bevestiging brief)

![Schermafbeelding 2022-01-24 om 12 10 40](https://user-images.githubusercontent.com/95683488/150772578-db2fbe33-dd99-4b02-846e-b46be39184b1.png)

Indien het hotel aangeeft dat ze een van deze mails niet ontvangen zijn dit de eerste stappen die je kunt ondernemen:
1 Controleer op bovenstaande plekken of het mail adres correct is.
2 Vraag aan het hotel of de mails niet in de Spam inbox terecht zijn gekomen.

Indien dit correct is of ze niet in de spam zijn gekomen kun je het volgende doen:
3 Vraag aan de IT van het hotel of ze kunnen kijken of de mails van protel afgewezen worden door de server.
4 Vraag aan de IT of ze een 'alias' kunnen maken voor het mail adres om te testen of het daarna wel werkt.
(meer info hierover: https://jira-live.protel.net/servicedesk/customer/portal/232/SUP-7774)

Indien het niet met een Alias werkt of dit geen optie is (ivm verzend adres protel) dien je het volgende te doen:
5 Maak een Jira ticket voor protel Duitsland met de vraag of ze kunnen controleren of het e-mail adres op de blacklist staat.
Benoem hierin de informatie die je in stap 1 tot 4 gevonden hebt.
(VB: https://jira-live.protel.net/servicedesk/customer/portal/232/SUP-310185)

**Comment by raoulhendriks** [comment]
Voor mij duidelijk.
Heb ook even het Jira ticket van Huize Koningsbosch, geplaatst bij stap 5
