### ISSUE TITLE
IDS | Log file lezen 

### ISSUE THREAD

**Issue by WillemFlow** [renskejetten/CUSTOMER-SUCCESS#78]
In de IDS heb je een kopje 'export log files'. Hierin kun je door te werken met filters benodigde data opzoeken.
Dit kan gaan om een in het verleden geëxporteerde prijs, beschikbaarheid of restrictie.

Het kan zijn dat de data niet naar voren komt omdat de log files te groot zijn.
Dan is het ook mogelijk om de 'rauwe data' te lezen in de xml log file. 
De meest recente log file vind je hier:

![log file](https://user-images.githubusercontent.com/95683488/150549805-e698d28a-af0c-4c32-b19f-920edbcf8c8c.png)

Een Log File uit het verleden vind je hier:

![Log file history](https://user-images.githubusercontent.com/95683488/150550475-19c39487-8744-49ad-ae13-e676df151d9a.png)

Als je op zoek bent naar specifiek data kun je het beste een handmatige push sturen speciaal voor dat tarief of kamertype. Dit doe je door in de PMS settings met je rechtermuisknop op het betreffende tarief te drukken en op 'Mark for full export' te drukken:

![Schermafbeelding 2022-01-21 om 16 09 07](https://user-images.githubusercontent.com/95683488/150550699-a67ab7d0-31da-4613-aff5-75067088ae50.png)

Als deze export uitgevoerd is kun je deze data gemakkelijk terug vinden in de log file. Deze staat onderaan.
De IDS exporteerd altijd per kamertype de tarieven. Je herkent de export aan de volgende regel in de file:
2022-01-21 15:10:31 : AE:ExportViaOTA_HotelAvailNotifRQ() : Exporting for RoomTypeID 61 (37391) - RateID 5 (0)
2022-01-21 15:10:31 : AE:SendOTAHotelAvailNotifRQ() : Request : **<OTA_HotelAvailNotifRQ ...... /OTA_HotelAvailNotifRQ>**

Dit is het request wat protel naar de channel manager stuurt. Hierop reageert de channel manager met een response:
Response : <?xml version="1.0" encoding="utf-8"?><OTA_HotelAvailNotifRS xmlns="http://www.opentravel.org/OTA/2003/05" Version="2.0"><**Success** /></OTA_HotelAvailNotifRS>

In dit geval heeft de channel manager dit dus met succes ontvangen.

De informatie die je nodig hebt staat dus in het request. Dit ziet er als volgt uit:

![Schermafbeelding 2022-01-21 om 16 15 03](https://user-images.githubusercontent.com/95683488/150551654-b0780a61-72c3-491f-883e-cd3a8fa6fb0f.png)

Dit kan wat onoverzichtelijk zijn in deze staat. Je kunt de gegevens kopieëren van < tot >:
<OTA_HotelAvailNotifRQ ...... /OTA_HotelAvailNotifRQ>

Dit kun je vervolgens plakken in de maintenance tab --> XML preview. De tekst uit de vorige afbeelding wordt dan overzichtelijk:

![Schermafbeelding 2022-01-21 om 16 17 19](https://user-images.githubusercontent.com/95683488/150554155-1118a122-f6f3-40ab-980a-3ef723b94928.png)

Je kunt nu de informatie lezen die je nodig hebt.

Naast het gebruik wanneer de Export log files tab niet werkt, kan dit ook gebruikt worden bij errors in de koppeling.
In het bestand kan er gezocht worden op bijvoorbeeld het woord 'error' om te zien waar het probleem ligt.

Het is mogelijk dat er een export error is:

![Schermafbeelding 2022-01-21 om 16 21 42](https://user-images.githubusercontent.com/95683488/150553788-2dd08676-f11f-4299-b28e-9e46e2c79ea7.png)

De meest voorkomende error is dat er een combinatie van een tarief - kamertype in de channel matching pairs staat, die niet meer geldig is. Dit kan zijn omdat het hotel het tarief verwijderd heeft uit de channel manager zonder ons in te lichten. Ook kunnen ze een kamertype van een tarief ontkoppeld hebben in de channel manager.

Dit ziet er als volgt uit:

![Schermafbeelding 2022-01-21 om 16 22 55](https://user-images.githubusercontent.com/95683488/150553014-0229877a-fa1d-450a-b204-626428efaade.png)

Het beste kun je hierbij zoeken op Error Code="630", dan vind je deze direct.

![Schermafbeelding 2022-01-21 om 16 24 50](https://user-images.githubusercontent.com/95683488/150553177-2cfc2242-88ee-4fa5-b202-a94c1e275525.png)

Dit los je op door deze combinatie uit de chm pairs te verwijderen:

![Schermafbeelding 2022-01-21 om 16 25 48](https://user-images.githubusercontent.com/95683488/150553534-a3e592a6-2edb-48ae-8edc-779546b788dd.png)

Loop zo een voor een de errors na tot de melding van de foute export verdwenen is uit de IDS.

**Comment by ZsuzsannaWu** [comment]
Hoe heb je de action monitor weer gekregen?

**Comment by raoulhendriks** [comment]
Goede uitleg Willem
