### ISSUE TITLE
PMS | Accounts receivable notes

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#81]
**Vraag**

Waar kan ik mijn notities noteren in mijn accounts receivable?

**Antwoord**

Deze kolommen worden zichtbaar wanneer een betaling/gedeeltelijke betaling wordt uitgevoerd waarbij de volgende velden worden ingevuld. 

Je gaat naar je accounts receivable en vinkt je rekening aan. Vervolgens klik je op post payment.

<img width="1642" alt="Schermafbeelding 2022-01-21 om 13 30 02" src="https://user-images.githubusercontent.com/72549907/150527404-f9f2b9d8-9fca-4cb8-91ab-b9e57a9f172c.png">

Nadien verschijnt er een pop-up van je post payment.

<img width="558" alt="Schermafbeelding 2022-01-21 om 13 31 00" src="https://user-images.githubusercontent.com/72549907/150527515-ae0df16c-ab30-46e1-8552-81b3fcf55d7c.png">

Je payment (betaalmethode) dient ook ingevuld te worden. Zo niet, dan kan dit niet opgeslagen worden.

<img width="1659" alt="Schermafbeelding 2022-01-21 om 13 31 34" src="https://user-images.githubusercontent.com/72549907/150527600-1ba7374b-e965-48ee-854d-6d807ba36fb2.png">

Je payment note komt overeen met wat je noteert in payment text. Notes komt overeen met wat je invult in comment.

Wat je wilt invullen kan je helemaal zelf kiezen. Mocht je dit nog graag willen testen, dan raad ik aan om dit in je trainingsversie te proberen tot dat je een goed resultaat bekomt.

**Comment by AudreyAdamus** [comment]
Dit wordt zelden gedaan of gevraagd. Ik denk dan dat dit wel voldoende informatie bevat

**Comment by TomMestrom** [comment]
Duidelijk
