### ISSUE TITLE
BWI | Push sturen in Memberweb

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#82]
**Situatie:**
Het hotel geeft aan dat bepaalde ingestelde tarief strategieën niet goed doorkomen.

**Oplossing:**
Vaak duurt dit een tijdje (ca. 30 min), dus vraag altijd wanneer ze dit hebben ingesteld. Als dit al eerder is ingesteld, check je natuurlijk of de restrictie goed is ingesteld.
Vraag ook precies welke restrictie voor welke periode.
Wanneer de restrictie dus niet gestuurd wordt, kan je het proberen om opnieuw te sturen.
Let op!:
Vul maximaal een periode in van maximaal *3 maanden*

Hiervoor ga je naar de CRS functies > Best Western Interface > Rate Sync
![Screenshot 2022-01-22 at 11 16 28](https://user-images.githubusercontent.com/95683711/150634579-5d327766-5db5-41d9-a2ea-e621d4ed3e56.png)
Vervolgens vul je de juiste data in, waarna je op 'send' kan drukken.
![Schermafbeelding 2022-02-01 om 10 46 18](https://user-images.githubusercontent.com/95683488/151946158-9b7285a8-8b74-4aa2-a2f9-116d71f60e63.png)

Dit werkt het zelfde voor de overige punten die daar op staan:
Beschikbaarheid:
![Schermafbeelding 2022-02-01 om 10 46 59](https://user-images.githubusercontent.com/95683488/151946290-37759425-9461-47bf-bc1f-aa3296a3cc1e.png)

Prijzen:
![Schermafbeelding 2022-02-01 om 10 47 08](https://user-images.githubusercontent.com/95683488/151946311-58b38a90-2bbc-4744-a85f-a6ea3281c619.png)

**Er is nog een manier om de restricties opnieuw te sturen, echter kost dit meer tijd:**
Een restrictie instellen in protel, restricties opnieuw verzenden, restrictie verwijderen, restricties opnieuw verzenden

**Comment by WillemFlow** [comment]
top
miss de andere functies ook doen? En dan deze link in de algemene memberweb zetten bij die punten

ZW thanks, welke functies zou ik nog doen?

**Comment by raoulhendriks** [comment]
''Je kan wel maximaal een periode van 3 maanden sturen.'' --> Vervolgens zie ik bij rate sync een periode van 1,5 jaar. 

Kan dit dan? of gaat die periode van 3 maanden ergens anders over?

**Comment by WillemFlow** [comment]
Nee kan niet, moet 3 maanden max zijn

**Comment by WillemFlow** [comment]
@ZsuzsannaWu ik bedoelde de prijs en beschikbaarheid
