### ISSUE TITLE
PMS | Passerby overschreven

### ISSUE THREAD

**Issue by ZsuzsannaWu** [renskejetten/CUSTOMER-SUCCESS#83]
**Situatie:**
Het hotel meldt: 'Onze standaard gebruiker van de passantenrekening staat op het moment op naam van ....'
Dus als ze een shop rekening openen, staat het profiel automatisch op een bepaalde gastenprofiel of bedrijfsprofiel, wat niet de bedoeling is.

**Oplossing:**
Dit wordt aangepast wanneer je een passerby invoice aanmaakt, vervolgens het profiel opent en de gegevens aanpast. Dit overschrijft dan ook de algemene gegevens, wat er voor zorgt dat vanaf dat moment dat de nieuwe passerby is.
Dus het standaard passerby (vraag aan het hotel welk profiel dit moet zijn, of leg uit hoe ze dit zelf kunnen doen) profile moet teruggezet worden op passerby:
Bijvoorbeeld het standaard passerby staat nu op 'Paul Abbot':
![op dit moment staat het verkeerd](https://user-images.githubusercontent.com/95683711/150635777-d2c0b793-17d0-4098-85a6-0a3e320c65ff.png)
Het moet standaard Flow BV zijn, dus ga je naar profielen en zoek je het juiste profiel op:
![zoek profiel](https://user-images.githubusercontent.com/95683711/150635780-8953aa50-36c4-40a3-a80e-d43f11617173.png)
Als je het profiel hebt geopend, kan je door middel van de 3 puntjes naast het type van het profiel 'set as passerby' selecteren, waardoor dit profiel je standaard passerby profiel wordt:
![set as passerby](https://user-images.githubusercontent.com/95683711/150635779-7cac3037-6985-4c03-a461-df726a494ec1.png)
![passerby profile](https://user-images.githubusercontent.com/95683711/150635778-a8db6cb1-a49a-4247-9e9d-92882c08b351.png)

**Intercom link:**
https://app.intercom.com/a/apps/fagrlzth/inbox/inbox/search/conversations/36000006960?q=passerby%20&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by TomMestrom** [comment]
Duidelijk wat mij betreft
