### ISSUE TITLE
Groepsreservatie niet kunnen linken aan MICE event

### ISSUE THREAD

**Issue by AudreyAdamus** [renskejetten/CUSTOMER-SUCCESS#84]
**Vraag**

Ik kan mijn groepsreservatie niet linken aan een MICE event. Hoe los ik dit op?

**Antwoord**

Wij zien dat er al een geannuleerde evenement is, #139. De groep was al hieraan gekoppeld.

![Schermafbeelding 2022-02-04 om 16 07 42](https://user-images.githubusercontent.com/72549907/152552914-f9fe6e30-1463-4823-bd6d-3b547290e0bc.png)
 
Voordat je de reserveringen aan de definitieve evenement kan koppelen, dien je ze dus eerst los te maken van de geannuleerde evenement:

![Schermafbeelding 2022-01-26 om 13 19 33](https://user-images.githubusercontent.com/72549907/151162406-851ee705-61ad-4dbe-8e1a-3e8389600762.png)

![Schermafbeelding 2022-01-26 om 13 20 17](https://user-images.githubusercontent.com/72549907/151161951-27346988-e134-4a70-91c1-521b9f21e6a3.png)

Vervolgens kan je je reserveringen toevoegen aan het nieuw MICE event.

Ik hoor het graag van je als het op deze manier lukt.

Met vriendelijke groeten,

**Link:** [Conversation with Véronique Dekoninck](https://app.intercom.com/a/apps/fagrlzth/respond/inbox/all/conversations/36000018130)

**Comment by raoulhendriks** [comment]
Hoe kan ik het snelste zien dat die groep al aan een evenement gekoppeld is?

**Comment by AudreyAdamus** [comment]
@raoulhendriks zo?
